### ISSUE TITLE
Suggestion for a nodejs/emeritus team

### ISSUE THREAD

**Issue by No9** [nodejs/admin#118]
Following up on 
https://github.com/nodejs/TSC/issues/301#issuecomment-381029448

While it was settled very amicably and I agree with the position from @Trott there does seem something quirky about the fact that a known contributor to the community cannot be recognised because they are not part of a current team.

In order to encourage a healthy contribution life cycle I'm opening this issue to suggest that we have a **nodejs/emeritus** team where people who have either held a position in the node.js org or have flagged to their current working team that they can no longer be an active participant can be placed so they are still recognised for their contribution while not having the fear of being relegated from the community. 

**Just say NO to BURN OUT**

**Comment by MylesBorins** [comment]
+1 as long as it is clear the emeritus team does not have the same access/
privledges as active collaborators (no access to moderation or travel.fund)

**Comment by gibfahn** [comment]
So basically nodejs/emeritus, but it doesn't inherit from nodejs/members? SGTM.

**Comment by mcollina** [comment]
sgtm
Il giorno sab 14 apr 2018 alle 14:46 Gibson Fahnestock <
notifications@github.com> ha scritto:

**Comment by ChALkeR** [comment]
SGTM, great idea! As long as that doesn't involve increased privileges.

**Comment by bnb** [comment]
For context, both the Community Committee and the TSC have the concept of emeritus.

My only concern would be that individuals who aren't active would theoretically have access to private repos within the org, which (afaik) we try to ensure are available to active contributors. I don't necessarily have an issue with this, though I think it could complicate the discussion around Moderation specifically. I _think_ this is what @ChALkeR was getting at.

So, I suppose this team could be the only exception to the new implementation of all teams being sub-teams of nodejs/members?

**Comment by Tiriel** [comment]
LGTM, provided the extended priveledges issue is dealt with (like it seems it will).

**Comment by WaleedAshraf** [comment]
SGTM 👍 +1

**Comment by gibfahn** [comment]
>So, I suppose this team could be the only exception to the new implementation of all teams being sub-teams of nodejs/members?

I think there are other teams that aren't under members, cc/ @Trott and @targos 

>My only concern would be that individuals who aren't active would theoretically have access to private repos within the org, which (afaik) we try to ensure are available to active contributors.

I think you have to specifically grant access to those repos, so if we don't do that we should be good (AFAIK).

**Comment by Trott** [comment]
> I think there are other teams that aren't under members, cc/ @Trott and @targos

That's right. Not all teams are subteams of nodejs/members, nor should they be.

> I think you have to specifically grant access to those repos, so if we don't do that we should be good (AFAIK).

Also correct.

**Comment by codeekage** [comment]
Should we ask those that will be part of the @nodejs/emeritus what they think of this decision so far? 

In as much as they won't be able to contribute to the node.js project to due reasons best known to them, which we should respect because when they had the time to make active contributions they did, in the best possible way within their capacity. 

I think people who should be promoted to @nodejs/emeritus (_must_) should have contributed significantly one way or the other to the Node.js Project. This way even if they say they can't do as much as before, we should still accept they timely contributions. 

This will also encourage a healthy ecosystem around the Node.js Project, _that your works while in the system will not be forgotten or tossed away because you are not able to be as active as before_.

Really don't know if this makes sense?

**Comment by ljharb** [comment]
Which contributions would you say are insignificant?

**Comment by codeekage** [comment]
> should have contributed significantly one way or the other to the Node.js Project. 

I'd like to stress the **_"one way or the other"_** every little thing you do is significant. From opening an issue up to holding a position in any of the WGs or Committee are all significant and this **_"one way or the other"_**  rules out any form of "insignificant" contributions.

**Comment by ljharb** [comment]
In that case, anyone who's ever been in the org theoretically has contributed significantly enough to warrant being on the emeritus team (when they're not on any other teams), yes?

**Comment by Trott** [comment]
@codeekage A group for Collaborators Emeriti would not necessarily be populated with people who can't or won't contribute. It would be people who no longer have a need or desire to participate as Collaborators on the main node repo. (Collaborators have push access to the repo, can start CI jobs, and can block or approve PRs.) There are a little over 100 Collaborators, but there are 872 contributors to Node.js during the last 12 months alone. Most contributors are not Collaborators.

Unfortunately, this is confusing because the word "Collaborator" is used differently in other parts of the project.

**Comment by Trott** [comment]
Whoops! Deleting my previous comment because I'm totally wrong, this is a different proposal than the "Collaborators Emeritus" one. This is more broad and @codeekage is closer to the mark than I am in my previous comment. Sorry for the noise.

**Comment by codeekage** [comment]
I think before someone says they cannot be as active as before, that shows some sign of "I was active, and now I can't do as much as I use to do" which usually done as an issue in the "*WG*"/"*Team*" they used to be on. Correct?

**Comment by mhdawson** [comment]
My thinking is along the lines of @ljharb. I could see that we'd have a documented list of all past/present contributors.

So when you are added to a team that does have elevated access, then you are added to the list.  If you later leave the team you stay on the list.  It would be less of an "emetrius" list but the total list of people of who have contributed to moving Node.js successful.  I like this approach because it mirrors what we do for code contributions (ie once you are added to the list of contributors to the code, you are never removed).

**Comment by feross** [comment]
Seems like there's consensus to make this happen. Let's do it?

**Comment by refack** [comment]
I'm 👍 on this. But to the issue of 2FA, could we exclude this team from this requirement (I can't think of a trick with the @&shy;members team)

**Comment by ljharb** [comment]
I'm not aware of any way to confine 2FA to anything less than "the entire org".

Either way, I don't think there's any value in making it easier for someone to have less security on their github account :-p

**Comment by bnb** [comment]
we haven't done this and AFAIK there are no plans to. I love the emeritus structures that we have built up, but this specific discussion does not seem like it's going to lead to further changes. Feel free to reopen if you feel like it will.
