### ISSUE TITLE
Draft Process for travel fund when visas are involved

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#135]
When individuals need to get visas to attend events there is a much longer timeline, more costs involved, and more paperwork.

It would be a good idea for us to document the process of determining if someone needs a visa and have different instructions / deadlines for these occurrences.

/cc @mrhinkle

**Comment by Trott** [comment]
Can you elaborate on this, maybe with an example of the problems that arise? I may be thinking too simplistically or something, but it seems like:

* Individuals need to know if they need a visa or not. That's information they have to figure out.
*Given that visas can add weeks to how long it takes for someone to be able to travel, they will need to ask earlier than others. But again, that's mostly on them to get the request in sooner. Once things have gotten to the point that someone may not be able to get a visa in time, there's not much to be done.
* Once they have a visa, the submission deadlines for expense reports would seem to be unaffected.

Maybe I'm not understanding the problems, but it seems like the main accommodation we'd need to make is allow people to request funds for travel with lots and lots of extra lead time. That's something we should try to do anyway for sure, but I'm not sure there's anything to do there other than for some folks who care about this stuff to make sure it happens. (Seems like a community-committee thing, maybe?)

The other thing we'd need to make sure is that requests for approvals don't get stalled, but we recently changed the process for expense approvals specifically to avoid them getting stalled because it was happening so much. I suspect we're OK on that one now.

**Comment by jakeNiemiec** [comment]
Consider that for some countries (like Germany) you need to have "proof of transportation / accommodation" (i.e. plane ticket) before you show up for your interview at the embassy (which you also need to pay for). If it is a business visa, you may also need to get documents or references to prove you are there for business. 👍 Thanks for the extra effort to include international folks.

**Comment by joyeecheung** [comment]
I've obtained my U.S. B1/B2 visa and Canada business visa with the help from the Node.js foundation (for previous NINA conferences) so I can help documenting the process.

Schengen visas are a bit more complicated and I got mine with only personal financial proofs, and I am not a lawyer so probably cannot provide much help with that.

**Comment by joyeecheung** [comment]
Also for business visa, based on my experience this is usually how it works:

1. Get funding to book flights and hotels
2. Get any other documents required to apply for visas, you can look it up on the websites of the embassies / the visa centers they have contracts with. In the case of business visas, an invitation letter from the foundation is necessary. If it's an event hosted by the foundation, you can just use https://events.linuxfoundation.org/visa-request/ to get a letter. In general you need to prove that you have a stable income (= bank statements) and strong ties to your home country, e.g. an employer, your family (letters with stamps, other types of official documents depending on your country).
3. Submit the application online. Some requires a face-to-face interview (e.g. U.S. for a Chinese citizen) so you'd need to prepare for another trip.
4. Submit your passport and have your biometric information collected in a physical place.
4. Wait for the approval. Also be prepared to write an appeal letter to the embassy in case your application is denied.

Also of course if you don't have a passport, you need to get one before submitting the visa request ;)

**Comment by codeekage** [comment]
Thank you @MylesBorins for bringing this up. It is really difficult to get a visa in Nigeria. 

It'll be lovely if NF could always help out with invitations and probably have collaboration with most embassies. 

This will make applying for a visa way more easier and getting folks to other nodejs events too.  Sadly because of the time frame left without an invitation, I might not be able to make it to the collab summit even when travel funds have been approved. 

I'll really appreciate if everyone could come together to see how we could assist people more.

**Comment by WaleedAshraf** [comment]
@codeekage I feel sorry for you. Here in Pakistan, the process is defined, but it takes some time (almost a month) to get VISA processed for Europe. And it was the one reason I didn't plan to attend Collab summit. (too late)

I'm not sure that Foundation would be able to make collaboration with embassies. I think that would be too much for Open Source foundation to take on. But I agree with MylesBorins post.

We can add some guidelines like, 
- If you need to get a visa, start at least 2 months ahead.
- Get a,b,c documents ready. 
- If applicable, get travel fund approval from the foundation.
- See if Foundation can write an invitation letter for visa processing.
- If travel funds are approved, see if the foundation can mention that in the letter. (helps in processing)
- Which type of visa is best suitable for attending open-source events/conferences. etc.

As most of Foundation events happen in Europe, Canada or USA. So we should only add guideline about these countries.

Once we have a document, people can contribute in adding more information in it.

**Comment by ChALkeR** [comment]
@MylesBorins @mrhinkle @hackygolucky I need to get an invitation for the travel visa again this time, but I wasn't able to find out whom I should contact about it :-/. I have the document from the previous year that worked for me back then, so I can email the example (and my personal details).

**Comment by chowdhurian** [comment]
I've had some experience navigating visas; I'll draft some language to get us started.

**Comment by AgenticHarness** [comment]
Reliable [travel planning services](https://myglobejourney.com/) can be especially helpful when individuals need to travel internationally for conferences, events, meetings, or professional activities. Visa requirements often involve additional paperwork, processing time, deadlines, and travel costs, so preparing everything in advance can make the journey much easier.

My Globe Journey provides professional travel services designed to help travelers organize their trips efficiently. International travel may require coordinating flights, accommodation, schedules, transportation, and other arrangements while also keeping visa-related timelines in mind. Having a well-planned itinerary can help travelers avoid unnecessary delays and make better use of their time and budget.

For people attending international events, proper preparation is particularly important because visa processing can sometimes take longer than expected. Travelers may need to confirm their destination requirements, arrange accommodation near the event, and ensure that their transportation and flight plans match their schedule. My Globe Journey helps make these travel arrangements more convenient by providing organized solutions for different types of journeys.

Whether the trip is for a business event, conference, professional meeting, or personal travel, dependable travel assistance can reduce the stress involved in arranging multiple details. With the right planning and support, travelers can focus on the purpose of their visit while enjoying a smoother and more organized international travel experience.
