### ISSUE TITLE
Moderation Policy goes against Code of Conduct

### ISSUE THREAD

**Issue by withinboredom** [nodejs/admin#147]
While reviewing the Code of Conduct and Moderation Policy, something seemed "off" about it.

Particularly:

https://github.com/nodejs/admin/blame/master/Moderation-Policy.md#L201-L206

> Note that Moderating non-Collaborator posts can often lead to retaliation or escalation of inappropriate behavior by the individual whose post is being Moderated. This is true primarily of individuals whose intent is to harass, disrupt or annoy individual members of the community. In such cases, it is best to handle the Moderation as quickly and as quietly as possible without drawing any further undue attention to the Post in question.

While the Code of Conduct says:

https://github.com/nodejs/admin/blame/master/CODE_OF_CONDUCT.md#L7

>a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation.

-----------

I'd argue that there's no recourse outlined (the word "repeal" doesn't appear in any of the texts), or due process for anyone who is not a "contributor." This seems to go against the Code of Conduct which is designed to protect everyone, "regardless of age" or "disability." I'd expect a young person to still be learning how to fit into a community, perhaps even, not realizing (how) they're being offensive to various actors in the community. They may very well retaliate because they do not know what else to do (and in-fact, there may very well be nothing else to do). After all, they're not as experienced as a more mature person might be.

I realize that is probably the vast minority of issues Moderators deal with, but that's what due process is designed to assist with: Minorities who are accidentally or intentionally mistreated by the enforcing actors, i.e., Moderators.

Personally, before contributing to this organization, I'd like to see that paragraph removed or edited, and replaced with some kind of due process that allows for the protection of the classes mentioned in the Code of Conduct. If there already is one, can it please be codified in the policies?

Sincerely,

Withinboredom

**Comment by MylesBorins** [comment]
/cc @nodejs/collaborators 

@withinboredom that paragraph is specifically talking about removing offending content. In my personal opinion I don't see the need for an extensive "repeal" process when it comes to removing content, that would seem more appropriate when someone is blocked.

We currently have [language](https://github.com/nodejs/admin/blob/master/Moderation-Policy.md#temporary-and-indefinite-blocks) around the difference between temporary and indefinite blocks, and people are able to repeal a block. Would more explicit language around how to appeal a block satisfy your concerns?

**Comment by benjamingr** [comment]
Thank you for raising this concern with us. I will bring this internally with the moderation team(cc @nodejs/moderation ).

Personally, I understand the concern about:

> I'd argue that there's no recourse outlined (the word "repeal" doesn't appear in any of the texts)

Would further clarification that users who have been moderated are welcome to report issues and reach out to `report@nodejs.org` help with that?

----

The amount of moderation actions taken has gradually declined over the past half a year. I personally think a big part of that is because we encourage self-correction and catch issues a lot sooner so fewer issues escalate.

We don't block lightly, we log every block we do and report it publicly to the TSC - you are welcome to go through all TSC agenda issues in https://github.com/nodejs/TSC and see for yourself who we have been moderating and how much.

Also, if you would like to get more involved yourself and help discuss our policies that'd also be great :)

**Comment by benjamingr** [comment]
What about:

 - Adding a sentence to https://github.com/nodejs/admin/blame/master/Moderation-Policy.md#L124-L129 
 elaborating on certain differences and how they might come off as deliberate attempts but might be misguided miscommunications.
 - Asking moderators to reach out to new blocked users who have non-new GitHub accounts (that is, not created in the last 2-3 days) and have an email listed and opening a communication channel with them.

Since we don't do a lot of blocking in general and most issues get deescalated I don't see #2 as a significant burden on the moderation team.

**Comment by dshaw** [comment]
After reviewing the text in question, I think we cover all the normative needs of Non-Collaborator Post moderation in bullet points under https://github.com/nodejs/admin/blame/master/Moderation-Policy.md#L175 and the paragraph at https://github.com/nodejs/admin/blame/master/Moderation-Policy.md#L201-L206 could be removed.

**Comment by Trott** [comment]
https://github.com/nodejs/admin/pull/159
