### ISSUE TITLE
How to officially request funds for things other than travel?

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#19]
I'd thought that the document added to this repo was for things in addition to travel, but I see now that it's not. I know that it's possible to request funds for things other than travel, but not actually sure what the process is other than "Open an Issue in node/admin".

Do we have a process documented anywhere?

**Comment by mhdawson** [comment]
We don't but we should.  I had asked on the foundation side at one point if @mhinkle could help flesh that out.

I think we can define the process on our side which I think should be opening an issue in the admin repo, getting some number of approvals, but then we need instructions for how to hand that off to the foundation to get things paid.

**Comment by hackygolucky** [comment]
My understanding here is that CommComm or the TSC, as top-level committees, should be requesting all funds via their Board representatives. Nothing should be spent ahead of time without prior approval. Generally speaking, in the past, the TSC has had some operational costs that have been allocated for ahead of time and that's why they have been reimbursed. But yes, it would be good for us to document this for any costs that any group would like to request/have considered.  :)

**Comment by jasnell** [comment]
I propose that the TSC Director, TSC Chair, CommComm Chairs, and Individual Member Reps work out and document what the process for this is and bring a PR.

**Comment by Trott** [comment]
AFAIK, TSC doesn't have a budget for things other than the money in the joint travel fund. I don't think CommComm does either. There's no joint budget beyond the travel funds (that I'm aware of). I think the process to ask for money for something is to propose something to the board. Anyone can do that in theory, but it will have more weight coming from the TSC, CommComm or (especially) both.

This has been dormant long enough that I think it warrants being closed. (If someone is going to actively agitate for more process around this or plans to actively work on this, then comment or re-open!) Hopefully the paragraph above is sufficient.

**Comment by MylesBorins** [comment]
@Trott that is not entirely accurate. There is a foundation budget for things outside of travel

/cc @mrhinkle

**Comment by Trott** [comment]
> @Trott that is not entirely accurate. There is a foundation budget for things outside of travel

Seems to be exactly what I wrote, so I would characterize it as entirely accurate. :-D

TSC and CommComm have no budget outside the travel budget (as far as I know). Money for anything else needs to be requested from the Foundation, not the TSC/CommComm. 

Ergo, I would conclude that the process is to ask the board for money when money is needed. That request can go through the TSC Director, the Executive Director, or really any method that will get something on the board's agenda.

That said, if @mrhinkle has some other process, yes, let's get that documented.

I do know that money was set aside for Code + Learn but with the education position being vacant, I don't think anything has happened there and I don't know how to request that money. (When the time comes, I would probably email the TSC Director and the Executive Director and ask.)

**Comment by Trott** [comment]
@MylesBorins Since this issue continues to attract no attention, as TSC Director on the Board, can you take on the task of finding out what the answer is and communicating it to everyone? Or, alternatively, if you think my conclusions above are sufficient, close the issue? (I'm fine with closing it as long as @bnb thinks the answer is sufficient.)

**Comment by MylesBorins** [comment]
Let's close the issue for now and I can follow up with @mrhinkle
