### ISSUE TITLE
Expand process around Collaborator CoC Violation reporting

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#21]
Currently our [process](https://github.com/nodejs/admin/blob/master/Moderation-Policy.md#collaborator-posts) dictates that there is a different process when moderating Collaborator's posts. It also outlines a process for following up when actions have been made

> Explanations of Moderation actions on Collaborator Posts must be provided in:
> * A new post within the original thread, or
> * A new issue within the private nodejs/moderation repository.

It does not appear that the current process is sufficient in outlining how the process should be handled when a complaint moves to multiple bodies (TSC / CommComm / Board). It also could use some more defined language on how we handle notification of the involved parties. Further, the process does not seem sufficient when we are dealing with members of leadership teams such as the TSC, CommComm, and the board.

I'd like to request @nodejs/moderation to put together some suggestions on this. Specifically I would like to see something that outlines the lifecycle of a complaint against a collaborator and a different lifecycle of a complaint against leadership.

For example:

### Complaints against collaborators
* Collaborator is notified of complaint
*  [How is decision made]
* Collaborator + Complainant are notified of the result
  - This should include timeline for updates if decisions have not been made
* Anonymized information regarding complaint is made publicly available
  - Is this desired or necessary?

### Complaints against leadership
* Leader is notified of complaint
* Board is notified that complaint has been made (anonymized?)
* [How is decision made?]
* Collaborator + Complainant + Board are notified of the result
  - This should include timeline for updates if decisions have not been made
* Anonymized information regarding complaint is made publicly available
  - Is this desired or necessary?
  - Seems more relevant for leadership then general collaborators

**Comment by othiym23** [comment]
It looks like you've got a pretty good start there, @MylesBorins – why not propose that as a PR and see what happens?

In general (and speaking only for myself) I'd prefer that @nodejs/moderation steer clear of _defining_ the policy under which it operates. I might have my own opinions, but in this role I think it's more important to focus on impartially _enacting_ the policies as approved. Building and maintaining the trust in the moderation team is my biggest goal for my involvement in the team, and to me this involves being pretty scrupulous about avoiding both the appearance and reality of taking the law into our own hands.

There are a few items on my to-do list that involve proposing some changes to the policies (mostly in response to discussions the team has had internally), but that's under the assumption that those proposals will be tweaked and ratified by whichever component of the organization's leadership owns the policy (one or more of the TSC, CommComm, and the Node.js Foundation board). There's a difference between making proposals and giving "expert guidance", and for whatever reason I'm more or less OK with the former but uneasy with the latter. Does that make sense?

**Comment by bnb** [comment]
Both as a moderation team member and a CommComm member, I am +1 to @othiym23's comments. @nodejs/moderation should ideally be a team that enacts the guidelines agreed upon by the bodies of the Node.js org (TSC, CommComm, Board).

This achieves two goals that I personally feel are important for the Moderation group. First, it enables the respective groups to define the policy, together. This enables buy-in from all parties and prevents one group from dictating how any other should act. I see this as a vital part of long-term sustainability for the project and the efforts we're currently enacting.

Second, it further enables the Moderation team to act by a set of rules that, again, the respective groups have agreed to be moderated by. This will help reduce friction for the Moderation team and enable us to be truly impartial when it comes to moderation actions - building trust with the respective groups.

**Comment by benjamingr** [comment]
We discussed this in the last meeting and agreed with @othiym23 that @nodejs/moderation should focus on enforcing policy and not defining it. I agree that there should be a process for discussing CoC violations with collaborators though.

**Comment by MylesBorins** [comment]
@nodejs/tsc @nodejs/community-committee could you chime in here please

**Comment by jasnell** [comment]
My hope would be that the moderation team would feel willing to provide policy recommendations. However, the actually policy decisions lie with commcomm and TSC jointly.

**Comment by bnb** [comment]
Both as a CommComm co-chair and a moderation team member, I do largely agree with @othiym23. Policy should be sourced from the bodies that the Moderation Team has been created to assist (TSC and CommComm). This effectively does two things: 

- Removes bias on the part of the moderation team
- Ensures that the TSC and CommComm are the source of their own policies.

The Moderation Team is enabled to act quickly and decisively. If the Moderation Team were to write or help write policies, there could be a possibility of bias on the part of the Team in that. This is a concern because the Team needs to be *entirely* abstract from politics and policy creation to ensure that it can be impartial - which is how it can do its job effectively. In the long run, if there is even a _possibility_ that the Team is impartial, this could be a source of conflict within the project and the broader Node.js community - which is exactly what the Moderation Team was created to help prevent.

We've already made great strides with our Moderation Team election process, enabling both the TSC and CommComm members to veto - effectively giving a blessing of trust to all team members from both the TSC and CommComm. This ensures that members are trusted to enact policies around Moderation effectively. 

That said, this same process should be applied to the _policies_ that are created - don't task the Moderation Team with them, but rather ensure that the TSC and CommComm are the source of the initial policies, and are in mutual agreement about them. If there is an issue that arises with the Moderation Policies, it will likely be funneled up through the TSC or CommComm. If these groups are the original source, they are the ones responsible for the policy and can effectively be held to it.

**Comment by hackygolucky** [comment]
I think we've talked about this in the various committees as well as within the Moderation Team, and as mentioned in a few different ways above, the Moderation folks were selected because of their expertise and are able to pull request a policy as much as any other relevant contributor. Due to the nature of Moderation, it was written and approved that no policy that is passed is passed without a general +1 from both TSC and CommComm, even if a Moderation team member were to draft a policy. This was written to ensure that those who are tasked ultimately with enforcement(the top-level committeees) feel accountability and ownership over the policies that are written. I think we're all in agreement here, so I'm happy to help draft this with you @MylesBorins.

**Comment by mhdawson** [comment]
+1 to putting together a draft we can review/comment on and  land.

**Comment by jasnell** [comment]
What is the next step on this? There does not appear to have been any further movement

**Comment by benjamingr** [comment]
Honestly when we've discussed this I recall a lot of arguments for "per case basis" rather than a general policy (where all the handling is reported to the TSC/CommComm anyway).

**Comment by bnb** [comment]
Additionally, there's the @nodejs/moderation team that was developed and launched since the last discussion on this. I think that team has a pretty good handle on this kind of thing, though would be interested in hearing if they have anything they'd like to add (as a member myself, I don't - but don't want to shut the door for others).

**Comment by Trott** [comment]
Seems like this can be closed at this point, but feel free to re-open or comment if you disagree.
