### ISSUE TITLE
More thorough support for Travel Fund recipients

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#239]
As we've continued to expand our contributor base beyond North America, we've begun gaining contributors who are from countries that have... difficulties with getting Visas approved.

With N+JS Interactive, there are at least two contributors that I know of who have either been rejected despite having the means via the Travel Fund.

Apparently LF policy prevents LF employees from assisting with this as a representative of the Node.js Foundation.

I would like to request that we build out policy to assist collaborators who are from distinctly underprivileged backgrounds when compared to the majority of the contributor base to ensure that they can actually _utilize_ the travel fund effectively.

This would _likely_ entail helping out Visa applications as necessary.

Whether this is on the Collaborator or Foundation side is a detail we'd need to figure out, but this is a massive hurdle that we can help our collaborators overcome.

**Comment by hackygolucky** [comment]
+1 to documeing these steps to the best of our ability and within our legal boundaries. 

I think an important thing to keep in mind here is managing expectations around folks with Visa needs as well @bnb. There are circumstances where we actually can't assist with visa applications. Requirements of this heavily depend on the country a person is living in -and- the country they are a documented citizen of.

**Comment by MylesBorins** [comment]
+1 on documenting

-1 on taking responsibility

We are not lawyers and need to be careful about offering what may appear to
be immigration advice

**Comment by joyeecheung** [comment]
Would be glad to help with the documentation. Off the top of my head, a standard invitation letter template and a channel to request them would help a lot (certain countries need them to be stamped and signed and be submitted in original so it involves more than just emails).

(Also, as someone who needs to apply for visa every time traveling to the Europe, I would be very grateful if there is help to make the process easier)

**Comment by hackygolucky** [comment]
So, right off the bat I know we can't offer a a standard invitation letter
template because that requires verification of a number of things including
the organization signing off on the person using the letter. That's a big
deal and you can get in trouble if you offer this to someone for whom you
haven't verified registration or speaking. So, I think we've already
highlighted we'll need to talk with someone at the LF/NF Events and Legal
to confirm what we CAN offer.

**Comment by WaleedAshraf** [comment]
I also agree with @hackygolucky that this is not a simple task as it's related to Legal stuff. I think there should be a team of 3/4 people? Who have some knowledge around VISA (where the event is happening). That team can help/guide contributors about which documents they should have to increase the chances of getting VISA.

**Comment by amiller-gh** [comment]
I think thats a great idea Waleed. We should empower 3-4 people who have gone through this process to come up with ways the process can be improved, and partner with the appropriate contact on the NF side to make recommendations where appropriate. 

Would love to see this spun out into a mini-initiative, like individual membership, to draft a collection of recommendations and update existing documentation. 

I think a lot can be accomplished by simply updating documentation, but there may also be important touch points with the Foundation where process can be improved too (ex: [visa request form improvements](https://events.linuxfoundation.org/visa-request/)). These parts of the initiative would partner with the NF/LF to recommend these changes to legal. 

Would someone on @nodejs/community-committee here be interested in taking point on organizing this?

**Comment by Bamieh** [comment]
Thanks @bnb for openning this issue 🤗 

I'd love to help out especially since I am directly affected by this, however my current schedule is a little bit busy so I wont be able to organize this 😞

**Comment by SarahKConway** [comment]
Here is the Visa information on the Node+JS Interactive website: 
https://events.linuxfoundation.org/events/node-js-interactive-2018/attend/visa-request/

**Comment by chowdhurian** [comment]
> Would love to see this spun out into a mini-initiative, like individual membership, to draft a collection of recommendations and update existing documentation.

The process that is defined by this initiative could be pulled into the CommonsJS that's been floated as a tangible benefit of a possible merge.

A travel fund that makes it **possible** for collaborators and members **from anywhere** to contribute **more effectively** to the Node.js and JS ecosystem could a cornerstore of a useful and inclusive CommonsJS.

Clarifying that, imo, there is real value is in giving this some priority over the next few months.

**Comment by ladyleet** [comment]
Hey all! I'm so happy to hear and see the community be so passionate about making sure we are an inclusive community and doing everything we can to support each other. This is one of the reasons I love the Node community!

Just wanted to jump in on the Linux Foundation/Node Foundation side! :) 

This process is documented in the visa process for LF events already but just to share in this thread and provide a few more little bits of info:

1) For LF events, LF will send a visa letter once registration has been verified.
2) LF can add travel date lines or change who the letter is addressed to if necessary.
3) If the Embassy contacts events@linuxfoundation.org to verify the authenticity of the letter, we can verify if we sent it.
4) We can provide an invitation letter which contains a bit more information about the event. We can also add in travel funding information.
5) LF can directly email the Embassy (registrant needs to provide email details) a visa letter.

The caveats are that LF is not in a position to contact the embassy on behalf of our attendees because in doing so, the LF becomes liable for that person's actions during the duration of their stay in the host country. Each embassy and country has difference requirements which would be impossible for us to track and maintain.

Unfortunately, community members cannot do additional leg work on the applicant's behalf either as they would be speaking on behalf of LF.

Let's continue the conversation though and see what else we can do to help support and everything, and I'm happy to answer questions on this side! ❤️ 😄

**Comment by Bamieh** [comment]
@ladyleet Thanks for you input. These details are actually very important to add in the [Travel Visas](https://github.com/nodejs/admin/blob/master/travel-visas.md) document.

**Comment by ryzokuken** [comment]
Hello everyone! @bnb thanks for kicking this off, and thanks everyone for having this discussion. This is something which has been troubling me recently and would be a very helpful first step towards being more inclusive and work around the troubling immigration procedures.

> Clarifying that, imo, there is real value is in giving this some priority over the next few months.

> Would love to see this spun out into a mini-initiative, like individual membership, to draft a collection of recommendations and update existing documentation.

Really love this idea. Perhaps y'all could hold a small-ish session to discuss this in the summit? Keep everyone who couldn't attend posted, and work on this for the next few months in order to have something tangible by the time we need a structure for JSI 2019.

> The caveats are that LF is not in a position to contact the embassy on behalf of our attendees

> community members cannot do additional leg work on the applicant's behalf either as they would be speaking on behalf of LF.

Thanks @ladyleet for jumping in from the LF side of things. While I realize the legal situation here and understand how it might be problematic for the LF to allow any of this (I think everyone else here does too), I guess it still doesn't hurt to discuss the issue at length and perhaps reconsider the status quo if required (hint: I believe it is).

>  impossible for us to track and maintain.

We have a huge community, and a great deal of talented people working on different community affairs. If it's impossible now, it's likely to stay that way if we never go around trying it in the first place. Also, I don't think the overhead would be as big as it seems from this statement. After all, they all might be different embassies, but they're all Canadian embassies and are governed by the IRCC. As long as the IRCC bottom-line is taken care of, most regional differences would be minimal, I believe.

**My two cents on this situation:**

In the past few weeks, I've read and talked extensively about the Canadian VISA "reforms" to people from both inside and outside the community and a lot of facts out there aren't exactly in our favor.
I'm open to privately sharing my findings, but if I had to summarize it (as it is mostly based off personally identifying information and stuff), I'd say that as long as LF does not expand the support it provides to collaborators visiting Canada for it's events, most collaborators (from specific communities and economic backgrounds) that had their VISA applications rejected this time around are likely to follow suit atleast for the next few years.

**Comment by codeekage** [comment]
I really do appreciate that this discussed, as I was directly affected and won’t be able to attend after so much preparation. 

From an economical background I’m from, its almost impossible to get a visa approved by an embassy, if whosoever inviting an individual is not taking responsibility to ensure their return. 

I know it’s almost impossible for LF to provide such  guarantee for a collaborator, but if we can have people in location of an event making sure and applying directly to the embassy on behalf of a collaborator, this goes a long way in achieving sorting out VISA issues for collaborators.

I’m happy to share my experience with embassies, as some reason are just bias and makes no sense to visa refusal.

**Comment by ryzokuken** [comment]
> I’m happy to share my experience with embassies, as some reason are just bias and makes no sense to visa refusal.

It was mind-boggling when it first happened to me. Hopefully we could chalk out a procedure to work around all the bias though.

**Comment by WaleedAshraf** [comment]
@amiller-gh I'm all in for separate initiative for this and to have a detailed documentation. I can manage time/effort.
I also (barely) got my VISA just 3 days before the event. 

Lets discuss this in our next meeting.

**Comment by bnb** [comment]
Going to put a slight hold on this until the next CommComm meeting so @SarahKConway and @ladyleet can join us to discuss with the CommComm 🙌

**Comment by ladyleet** [comment]
👍

**Comment by amiller-gh** [comment]
Action Item from today's meeting: @ladyleet and @SarahKConway will set up the new `visas@nodejs.org` email alias to help answer support questions. Unfortunately, other than potentially small tweaks to folks' letters, there isn't a whole lot the Foundation can do to help expedite the process. However, this comms channel will be important to members struggling with visa applications feel supported as they navigate the process.

@WaleedAshraf, once this is set up lets update the visas documentation in nodejs/admin and call this ticket finished 👍

**Comment by keywordnew** [comment]
I believe we've made progress on this front. The OpenJS Foundation has begun supporting attendees (https://github.com/nodejs/admin/blob/master/travel-visas.md#need-some-assistance) and folks had made use of this by Collab Summit Berlin 2019. 

After the Travel Fund formally moves to the governance of the CPC via #398, further issues for the Travel Fund can be opened in the CPC. In the meantime, the Travel Fund continues to be the responsibility of nodejs/admin.

I'm closing this for now, feel free to reopen anytime.
