### ISSUE TITLE
We should all talk about expectations of the moderation team

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#24]
edit: accidentally submitted with 0 content, sorry

I think the @nodejs/tsc @nodejs/community-committee and @nodejs/moderation should get together and discuss what the expectations of the team are and update the copy [in the moderation policy](https://github.com/nodejs/admin/blob/master/Moderation-Policy.md#moderation-team)

I'd like to suggest making a working session open to all members of each team, use that session to produce updated copy, and then get all groups to sign off on it

Thoughts?

**Comment by othiym23** [comment]
I'm not sure a big-bang "constitutional convention"-style kickoff is necessary, and have some concerns that it could prove to be counterproductive. There's already a clear and reasonably complete moderation policy that seems sufficient as a charter for the needs of @nodejs/moderation. There are certainly areas where it could be clarified, and the connection between the policy and the moderation repo could be made more explicit, but I think the best way to do that would be through PRs against the existing policy. Since the policy is located here, and this is a location that all interested parties can watch, why not try that and see how it goes?

**Comment by MylesBorins** [comment]
@othiym23 it seems like I perhaps have not done the best job of communicating

I completely agree that we don't need to re-evaluate all the things.

What I think could be useful is having a meeting with enough stakeholders from all committees where the moderation team gives an update on the role they see themselves filling, reviewing the existing documentation, and updating it as necessary

Does that seem reasonable?

**Comment by othiym23** [comment]
I still would prefer to do things via a PR / proposal + discussion process.

There are [several](https://github.com/nodejs/TSC/issues/384#issuecomment-337664902) [recent examples](https://github.com/nodejs/TSC/issues/384#issuecomment-337543062) of face-to-face meetings that have resulted in miscommunication and crossed signals, in part because the meetings weren't held in a manner or forum that were convenient for the consumption of parties who didn't take part. Even if such a meeting is recorded, the process is inherently less transparent than having discussions on a public forum like this one, with discussions that can be quoted and referenced. Also, when the goal is incremental progress rather than some kind of de novo establishment of an organization, meetings – particularly meetings with as many participants as you've proposed for this one – can be slow to establish consensus and bring with them a high degree of organizational overhead I'd prefer to avoid.

**Comment by benjamingr** [comment]
I think there is merit in talking to people face-to-face that want to help shape the way the moderation team sees itself and define its agenda well while acknowledging that for actually policy forming we need to use the PR / proposal + discussion process. Especially when those people are in the TSC/CommComm and have a direct influence over the policy forming itself.

**Comment by MylesBorins** [comment]
FWIW I think this meeting should be publicly broadcast with open Q/A at the end. I've found that a single meeting where we get to talk can be more productive than a dozen threads

**Comment by Trott** [comment]
Is this close-able?

**Comment by MylesBorins** [comment]
I'm not sure tbqh. If the moderation team thinks it is I won't object but I still don't personally have a insight into what the goal and agenda of the moderation team is

**Comment by ryanmurakami** [comment]
Revisiting this. @MylesBorins, has your insight changed over the last few months? If not, do you think it would be helpful for a Moderation Team member to present to the TSC/CommComm?

**Comment by MylesBorins** [comment]
@ryanmurakami I'm going to close this. Things have been working afaict and @Trott has been giving ongoing updates
