### ISSUE TITLE
creation of whatwg-stream repo and npm module

### ISSUE THREAD

**Issue by mcollina** [nodejs/admin#262]
I would like to create a repository, a team and a corresponding npm module named `whatwg-stream`, under the node org.

See https://github.com/nodejs/open-standards/issues/12 for more details.

cc @joyeecheung

**Comment by benjamingr** [comment]
I'd love to be a part of this. Also: cc @devsnek

**Comment by joyeecheung** [comment]
A bit of bikeshedding: is it going to be `whatwg-stream` or `stream-whatwg`? Asking because we are likely to follow this convention when we want to implement other WHATWG thingy later. `whatwg-*` may be sorted better and easier to search I guess, but we use the [`url-whatwg`](https://github.com/nodejs/node/issues?q=is%3Aopen+is%3Aissue+label%3Aurl-whatwg) label in core for WHATWG URLs - that can be easily modified, though

**Comment by devsnek** [comment]
what if we just put our modules in the open standards group repo, as a monorepo

**Comment by joyeecheung** [comment]
@devsnek I'd prefer we don't do that: the last time we talked about the monorepo idea in automation, it never really went anywhere, also, it would be difficult to mange the commit and release access if we start out as a monorepo.  I'd suggest we start small and just manage the repo separately for a start, otherwise we may be stuck at getting the tooling and process ready instead of doing actual experimental work. It's not going to be too late if we want to merge multiple repos into one later.

**Comment by mcollina** [comment]
I think monorepo are great if you want to have a single release and testing process. I don’t see how it would be the case for other standards-related modules.

I proposed whatwg-stream because of readable-stream. I’m really not fond of the name, so any help in that regard is welcomed.

**Comment by jasnell** [comment]
+1 to a new repo for whatwg streams (whatever y'all wanna call it).

**Comment by dshaw** [comment]
+1 for creating the repo. +1 for `whatwg-stream`. -1 for monorepo, we're too loosely coupled for that to be effective IMO.

@joyeecheung Perhaps we can update the `url-whatwg` to be `whatwg-url` for symmetry.

**Comment by mcollina** [comment]
Repo and team created! We can always change the name later on.

**Comment by joyeecheung** [comment]
I've renamed the `url-whatwg` label to `whatwg-url` in core, FWIW (this does make it more aligned with what we have in the test names)
