### ISSUE TITLE
Add Google-Cloud-Build to github marketplace for Node.js org

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#298]
We are looking at using this tool to automate deployment from the new website-prototype repo. It would only be authenticated for the website-prototype repo. Any objections?

/cc @nodejs/build 

Refs: https://github.com/marketplace/google-cloud-build

**Comment by amiller-gh** [comment]
Psyched for this to be a part of our workflow – no objections here.

**Comment by refack** [comment]
I have a few questions:
1. What is the added value over the currently available tools (Jenkins/Travis/"the bot")?
2. Who will be responsible for maintenance of this integration?
3. Where will it deploy to, and who is responsible for it's maintenance?

**Comment by MylesBorins** [comment]
1) we are looking at using `firebase-hosting` to simplify deployment. Using cloud build will allow us to automate the deployment on pushes to master without requiring any keys to be maintained within the repo (all handled via IAM)

Aside from that cloud build is a very robust service for building CI / CD with docker... I think we could definitely explore this system for other build infrastructure and am finding out if we can get a sizable credit from google to support this work

2) I am setting it up and taking responsibility for this initial deployment. We can choose to move to different infrastructure at any point. This has a shipping deadline of Feb 12th, so I wanted to simplify deployment without relying on any other team members (unfair to push short turnaround)

3) I've set up a "nodejs-infrastructure" project on GCP. I'd be happy to share admin rights with all of build once I figure out the billing.

**Comment by refack** [comment]
> get a sizable credit from google to support this work

👍 

Thanks for the response.
I do believe this should be discussed with the build WG (I can bring this up today at https://github.com/nodejs/build/issues/1667)

**Comment by MylesBorins** [comment]
fwiw I just got $1k approved for us to "experiment with". We can ask for more (if necessary) when we figure out what our needs are going to be.

**Comment by rvagg** [comment]
One of the problems we keep bumping up against is the monolithic nature of our website setup and the lack of flexibility it affords given the security concerns and therefore the limited number of people that can access anything. A goal we have is to pull it apart and make the various components and tasks it performs more independent so we don't have one big set of _crown jewels_.
So, moving ahead with new website prototyping on entirely separate infrastructure is likely going to help move in the right direction--as long as we're all conscious of this need.
My only concern is with vendor lock-in (because let's be honest, Google likes to do things its own unique way) and being locked into a platform that places even more restrictions on who has meaningful access to help administer. It's early, so I don't want to overthink that in this case and am not suggesting this is a blocker, just a concern to be mindful of. As long as we rely on open technologies then it hopefully won't be too hard to make infra changes if we find ourselves backed into a corner.

**Comment by mhdawson** [comment]
Is this for the "web site redesign" or the .dev website which is not the "new" website but something that will be in parallel with node.js org and possibly consumed by node.js or the "web site redesign" at some point.

**Comment by MylesBorins** [comment]
this is about the https://github.com/nodejs/website-prototype, something that will be in parallel with nodejs.org.

**Comment by amiller-gh** [comment]
My hope for the property is that it will become a staging ground for the website redesign work moving forward, but as Myles put very well – there is a lot more complexity in pulling that off.  I'm working on a project plan to get the rest of the planned new website content out the door after the single pager launch that I will shop around once ready, but for now, the goal is just to host this "Getting Started" single pager.

**Comment by MylesBorins** [comment]
As it doesn't appear there are any objections I would like to execute on this tomorrow. Please chime in if you have concerns

**Comment by MylesBorins** [comment]
All done everyone, thanks!
