### ISSUE TITLE
Intent to create new nodejs.dev maintainers team

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#307]
We have a bunch of people contributing to the new nodejs.dev site and I would like to invite some of them to be collaborators, but don't want to extend the permissions to out of scope repos.

Planned name `nodejs-dev-maintainers`. If there are no objections by Monday I plan to create the team

**Comment by addaleax** [comment]
SGTM. As far as I am concerned, you don’t need to wait until Monday.

**Comment by MylesBorins** [comment]
@addaleax do we have a policy around making groups? I was trying to follow a similar process to making a new repo. Happy to do it sooner

**Comment by ahmadawais** [comment]
🙌 I'd love to help :)

**Comment by addaleax** [comment]
> @addaleax do we have a policy around making groups?

Not that I am aware of.

> I was trying to follow a similar process to making a new repo. 

I don’t understand *why* we have that one either, but yeah, I understand. But I’d also say the lack of rules around teams makes this your call.

**Comment by codeekage** [comment]
Should we establish rules for team creations? 

(Of course after landing this)

@nodejs/community-committee @nodejs/tsc

**Comment by joyeecheung** [comment]
> Should we establish rules for team creations?

There was a proposal https://github.com/nodejs/admin/issues/282 which I have not been able to get back to (the ETA was February but I've been stuck with other work, sorry!). The general idea of that proposal is recommending administrators to wait until a contributor actually contributes to some work publicly tracked by GitHub until they perform the action of adding them into the organization, instead of straightly adding people without any observable contributions. The other parts are mostly formalities.

**Comment by codeekage** [comment]
IMHO, this should be labelled `cc-agenda` and `tsc-agenda` referencing #282 in our next meetings. 

@joyeecheung good work with #282 (hat tip 🎩) 

Since this team being created was mentioned in #282 I think we should first move forward with implementing #282 while collaborations can still continue in the existing repo temporarily.

At least, this will be a good way to iterate and experiment #282, if this is something we’ll want to keep or otherwise.

**Comment by joyeecheung** [comment]
FWIW I don't think I'll have time to implement steps 2-4 mentioned in the OP of https://github.com/nodejs/admin/issues/282 until April - any help would be very welcomed, but I don't want to block the creation of the nodejs.dev team because that proposal only intended to add a recommended workflow instead of something mandatory anyway. Most of the pending work are just formalities.

**Comment by mhdawson** [comment]
+1 for creating the team.

**Comment by MylesBorins** [comment]
@codeekage I don't think we need to add this to the agenda of either groups if we can reach consensus in the repo

I opened https://github.com/nodejs/admin/pull/308 which simply follows the current timelines we have in place for repos

**Comment by codeekage** [comment]
+10000 @MylesBorins

**Comment by MylesBorins** [comment]
Sent out the invites to people who have been active in the repo. 5 current organization member and 7 new folks. Will work with group to determine governance around inviting new folks before invite more.

Made nodejs.dev team a subgroup of members. If anyone disagrees with this please lmk. To remind y'all that does give access to moderation repo.
