### ISSUE TITLE
Board representative for Node.js

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#364]
Now that the CPC has been fully bootstrapped its probably time to discuss how to elect the board representative for Node.js.  As per the CPC charter (https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#section-8-board-representation)

>For the first year after the formation of the OpenJS Foundation, the processes for filling this seat will be as follows:

>As a constellation member of the OpenJS Foundation, the Node.js project will elect one Board representative from either the Technical Steering Committee (TSC) or Community Committee (CommComm). The representative will be selected according to a process defined by the TSC and CommComm.

Since this is a single board representative from across the project, both the TSC and CommComm need to agree on how we want to elect that representative.

@nodejs/tsc , @nodejs/community-committee any volunteers to take a first cut at documenting the process we'll follow?

**Comment by jasnell** [comment]
Let's keep it simple... Open a nomination period where any @nodejs/tsc or @nodejs/community-committee member may self-nominate for the position, followed by a vote conducted the same way we've done previously.

**Comment by cjihrig** [comment]
I like @jasnell's suggestion ^

**Comment by MylesBorins** [comment]
+1 to sugestion from @jasnell

**Comment by keywordnew** [comment]
+1 to suggestion above by @jasnell

To further the original proposal by @mhdawson, we can document this in
parallel even as the nomination period is initiated right here in
nodejs/admin.

**Comment by danbev** [comment]
+1 to @jasnell's suggestion

**Comment by Trott** [comment]
> Let's keep it simple... Open a nomination period where any @nodejs/tsc or @nodejs/community-committee member may self-nominate for the position, followed by a vote conducted the same way we've done previously.

We can't do "a vote conducted the same way we've done previously" because both committees have to agree on a single representative. Unless I'm mistaken, we've never had a combined-vote for a single candidate. The obvious options are:

* each committee has equal voice

OR:

* each member of each committee gets one vote

If we do one-vote-per-member, it favors TSC because TSC is larger. That doesn't seem fair to me (which I say as a TSC member).

But if the committee's are weighted equally, the TSC can vote and pick someone, and CommComm can vote and pick someone. What do we do if they don't pick the same person? Have a plenary session and hope we can hash it out?

**Comment by hackygolucky** [comment]
A lot of feels here because we've seen elections at various levels play out in weird ways over the years in Node.js. Outside of very special circumstances unrelated to electing a liaison to the Board, as @Trott said we've never actually had to elect a single person together to represent all of our work/needs on a Board. It's why we eventually broke out Community Committee into a top-level committee.

Elections with one vote to person ends up causing some hazardous behavior in trying to fluff numbers to get representation(this also assumes people actually try to do this and it's a LOT of work and obviously causes complications at the committee level but you do you and assumes we aren't all acting in good faith). I'd also like us to avoid popularity contests, which was expressed as a serious issue in the Individual Membership elections in some years.

We've used a number of systems between TSC and CommComm. Helios(Individual Membership prior), decing.com, CIVS. 

My recommendation here is using a system like decing.com or CIVS with the settings that allow for each voting member to vote(their vote gets counted as equally weighted to others voting) by stack ranking nominees. 

Thoughts?

I also recommend a subgroup that helps make sure we've messaged what the role of this person on the Board would be, as I've stated previously, Board work is a very particular beast that is pretty different skills-wise than most work we do in the project and even amongst the projects in OpenJS.

**Comment by hackygolucky** [comment]
I would go so far as to argue that prior Board representation should draft this work given the information we know about the experience @MylesBorins, @williamkapke. @jasnell , Rod, Feross, and Ashley.

**Comment by MylesBorins** [comment]
I will definitely be making myself available to help support the incoming community board member. Drafting the work and expectations is a great idea. One thing that may be helpful is getting the committees to document what their need / expectations are as well.

+1 to CIVS, we've used it before and it works. TBH we could potentially start getting volunteers to raise their hands in advance... if we don't have multiple candidates (which was the case in past elections) we may not even need a vote.

**Comment by mcollina** [comment]
+1 to get nominees early and +1 to a vote per individual, whatever that
system looks like. I think being on the board is a different job from both
TSC and CommComm responsibilities, and we should pick someone willing to
take those on.

We are going to have to manage board updates differently, likely via emails
sent to both tsc and commcomm at the same time.

Il giorno gio 16 mag 2019 alle 13:43 Myles Borins <notifications@github.com>
ha scritto:

**Comment by jasnell** [comment]
I'm not particularly concerned with the actual voting process. While we determine that, however, we should start soliciting self-nominations.

**Comment by jasnell** [comment]
@nodejs/tsc @nodejs/community-committee ... ping. Just want to make sure this continues moving forward.

Disclaimer: I will be putting my name into the hat for consideration as the board representative so I'd like to get an idea of when the nomination period will be opened.

**Comment by mhdawson** [comment]
Given that many people will be travelling for the Collab Summit and JSConfEU next week what I'd suggest is that we open nominations May 4 and leave them open for a week.  This will let us publicize at the Collab summit and give people some time to consider if they'd like to volunteer.

I'll also add a Disclaimer since James has that I'm also considering putting my name into the hat for consideration.

**Comment by jasnell** [comment]
I assume s/May 4/June 4 ? ;-)

**Comment by mhdawson** [comment]
@jasnell oops, yes, will edit above.

**Comment by jasnell** [comment]
@nodejs/tsc and @nodejs/community-committee ... @mhdawson put out an official call for self-nominations via email this morning. I want to formally put my name in the hat. My primary interest in representing the project on the Board at this time is to ensure that the overall direction that the Foundation is taking represents the best interests of the project as a whole. There are several initiatives, just as the long awaited Certification, the Interactive event, and travel fund, as well as ecosystem wide concerns such as package maintenance and sustainability that require champions on the Board. The more we have, the better.

**Comment by mhdawson** [comment]
I'd like to add my name to the hat as well.

I'm interested in representing the Node.js project on the Board and think I'm well positioned to be able to do that effectively.  I'm on both the TSC and Community Committee which will make reporting/gathering requests easier.  I'm also active across a good number of the teams and working groups which will make it easier for me to reflect the needs of those teams as well. 

My goal as a board member would be to: 
* ensure the needs of the Node.js project are considered in the decisions that are made;
* help the board understand and incorporate any issues raised within the project; and
* help champion some of the broader/longer term initiatives that are important to the success of the 
  project in the long run.

It's also a growth opportunity for me as even though I've worked with the Foundation staff and board members on some initiatives, I've not been part of a board for a project like this and am interested building my expertise in this area.

**Comment by mhdawson** [comment]
@nodejs/TSC, @nodejs/community-committee a reminder that the period for nominations for Node.js board directory ends tomorrow based on the proposal in https://github.com/nodejs/admin/issues/364#issuecomment-495782009.  If you are interested please dd your nomination to the issue.

**Comment by mhdawson** [comment]
Next step is to figure out how to run the election.  I'd like to abstain from that to avoid any perceived potential conflict of interest.

@joesepi, @mcollina as our CPC reps would one of you two be able to push it forward?

**Comment by bnb** [comment]
I'd like to suggest https://civs.cs.cornell.edu/. It just works in most cases 😄

**Comment by Trott** [comment]
> I'd like to suggest https://civs.cs.cornell.edu/. It just works in most cases 😄

Tools are nice and everything, but a mere implementation detail. The vastly more important, urgent, and fundamental decision is about how votes are to be counted.

One person = one vote? Lots of upsides, but the potential downside is that it significantly favors the TSC because the TSC has more members.

Each committee selects their preferred candidate? Big downside is we basically have to hope that both committees select the same person because otherwise, we probably end up deciding with a coin flip or something arbitrary like that.

Something else? Big downside is that there isn't an obvious "something else".

**Comment by bnb** [comment]
ah apologies. Read @mhdawson's comment independently of the rest of this thread ❤️ 

I do not personally mind if 1 person = 1 vote. Contributors are all humans, and all contribute to the project at the highest level – in the end, we're one team. 

Dividing a line of "these committees are equal regardless of the individuals working in them" pushes the concept that the teams have independent and unique goals, rather than the same goals. We do _work on different things_, yes, but they're all working toward the same goal.

This individual representative from Node.js to the OpenJS Foundation Board will be the one representing that shared goal from the project. IMO, every one of us is responsible for picking the most effective individual to represent that goal to the Foundation.

**Comment by bnb** [comment]
Also to address the "something else" point: there's a tool we used previously in CommComm votes that allowed vote weighting. Highly manual data entry and voting but it could be used to weight CommComm and TSC votes to be equal as whole committees.

That said, I'm in favor of the simpler and more community-centric approach.

**Comment by Trott** [comment]
> ah apologies. Read @mhdawson's comment independently of the rest of this thread ❤️
> 
> I do not personally mind if 1 person = 1 vote. Contributors are all humans, and all contribute to the project at the highest level – in the end, we're one team.
> 
> Dividing a line of "these committees are equal regardless of the individuals working in them" pushes the concept that the teams have independent and unique goals, rather than the same goals. We do _work on different things_, yes, but those things are all working toward the same goal.
> 
> This individual representative from Node.js to the OpenJS Foundation Board will be the one representing that shared goal from the project. IMO, every one of us is responsible for picking the most effective individual to represent that goal to the Foundation.

I find this reasoning compelling and am currently +1 on one-person = one-vote. I also think it's just better than the alternative, even if you think it's imperfect. It's also somewhat simpler.

**Comment by MylesBorins** [comment]
+1 to one person 1 vote

**Comment by joesepi** [comment]
Let's have a vote on how to vote and then proceed.

Please respond to this comment with your vote:
🚀- 1 person 1 vote
🎉- some sort of weighted voting system

**Comment by joesepi** [comment]
There seems to be no objection, so I will move forward with creating an election using CIVS where 1 person = 1 vote.

@mcollina or I will respond soon with details and such. Thanks.

**Comment by joesepi** [comment]
Hey yall. Just some housekeeping here on the election.

- I'll use the CIVS system for this election
- I will try to get this election up and running today or tomorrow.
- I will set the election to last 2 weeks from the start date
- I will add each member of the tsc and comm comm to the private election "poll" and the system should email each of you a unique URL
- The two nominees are James Snell and Michael Dawson
- I'll open an issue for each nominee in this admin repo where a candidate's statement can be added and any Q&A can be directed

Am I missing anything? Any objections, questions, comments to the above?

Thanks.

cc/ @mcollina @jasnell @mhdawson

**Comment by mhdawson** [comment]
Looks good to me.  I think we may have only had the elections open for 1 week in the past but I'm also ok with 2.

**Comment by joesepi** [comment]
The election for a Node.js board seat on the OpenJS Foundation's Board of Directors is underway!

I've created the private election poll in CIVS. A unique URL to vote in this election should have been sent to each email address in these two lists:
https://github.com/nodejs/node#tsc-technical-steering-committee
https://github.com/nodejs/community-committee#community-committee-members

I've also created two issues in this nodejs/admin repo for each of the candidates. Each issue has the candidate's statement as submitted above and is open to Q&A. Candidates, if you'd like to update your statement, I'm happy to assist if needed.

- James Snell @jasnell https://github.com/nodejs/admin/issues/375
- Michael Dawson @mhdawson  https://github.com/nodejs/admin/issues/376

I've set the voting to end two weeks from today at 5pm EST. (July 5, 2019, 17:00 EST)

To be fully transparent: I have been working with Matteo Collina on this election and we have been reviewing and approving each others steps through the process. Any questions, comments or concerns, please feel free to reach out to us @joesepi & @mcollina 

Happy Voting! 🎉 

/cc @nodejs/tsc @nodejs/community-committee

**Comment by joesepi** [comment]
Reminder that the voting ends this Friday 5pm EST. (July 5, 2019, 17:00 EST)

So far, only half of the folks able to vote have voted.

@nodejs/tsc @nodejs/community-committee

**Comment by joesepi** [comment]
The election for the Node.js seat on the OpenJS Foundation board has concluded.

Matteo (@mcollina) and I would like to thank both candidates for stepping up to represent Node.js in this capacity. Both candidates are respected leaders in the community and we greatly appreciate their past and future work.

The person with the most votes is **Michael Dawson**.

Thanks to everyone who participated and thanks to Matteo for working with me on the election.

Details:
> Candidates: James Snell (@jasnell), Michael Dawson (@mhdawson)
> Private poll
> Authorized voters: 30 (Node.js TSC + Community Committee)
> Actual votes cast: 21
> Election open for 2 weeks.

@nodejs/tsc @nodejs/community-committee

**Comment by mcollina** [comment]
Closing because the 2019 election happened.
