### ISSUE TITLE
Q&A with Michael Dawson – OpenJS Board election

### ISSUE THREAD

**Issue by joesepi** [nodejs/admin#376]
Per https://github.com/nodejs/admin/issues/364, we are opening up the election for the Node.js project board seat on the OpenJS Board of Directors.

Welcome to the Q&A session for nominee Michael Dawson @mhdawson!

@nodejs/tsc and @nodejs/community-committee please ask your questions of this nominee in this issue. You will find a link to the CIVS election poll in your email inbox.

CANDIDATE STATEMENT:

> I'm interested in representing the Node.js project on the Board and think I'm well positioned to be able to do that effectively. I'm on both the TSC and Community Committee which will make reporting/gathering requests easier. I'm also active across a good number of the teams and working groups which will make it easier for me to reflect the needs of those teams as well.
> 
> My goal as a board member would be to:
> 
> - ensure the needs of the Node.js project are considered in the decisions that are made;
> - help the board understand and incorporate any issues raised within the project; and
> - help champion some of the broader/longer term initiatives that are important to the success of the project in the long run.
> 
> It's also a growth opportunity for me as even though I've worked with the Foundation staff and board members on some initiatives, I've not been part of a board for a project like this and am interested building my expertise in this area.

**Comment by gireeshpunathil** [comment]
- from what source(s), and through what methodology(ies), will you gather needs of Node.js project?
 - it is rare to have unanimous opinion among members on project's issues or topics. how will you drive convergence?
 - you may be `owning` and driving one or more initiatives in the project. how will you position Node.js' collective priority on top of yours?
 - how will you pursue node's interest with board?
 - how will you assess implications of board's direction / decision to Node.js project?
 - how will you tackle situations wherein Node.js' interest is orthogonal to that of the larger JS ecosystem?
 - what will you define as success criteria of your role in the board representing Node.js?
 - what, in your opinion, are the top n advantages of Openjs foundation to the Node + JS ecosystem?
 - what, in your opinion, are the top n priorities of the Node.js project at the moment?

**Comment by mhdawson** [comment]
Took me a bit of time here is my first cut. @gireeshpunathil thanks for the great questions and let me know if you have any follow on questions.

> from what source(s), and through what methodology(ies), will you gather needs of Node.js project?
* I will gather/understand the needs of the Node.js project through participation in the teams and
  working groups, the TSC and Community Committee as well as watching the issues across the 
  repositories within the organization. 
* I will talk to those participating and leading the efforts that I am not able to be as directly involved
  in order to get their perspectives.
* I will look for opportunities to implement processes that help needs to be voiced or recognized 
  through discussion (github or other). For example, our documented list of strategic initiatives and the 
  review we do periodically in the TSC and Community Committee meetings.
* I'll continue to maintain the project board that Myles put in place for tracking issues that need to be   
  brought to the board.

> it is rare to have unanimous opinion among members on project's issues or topics. how will you drive convergence?
* Our consensus seeking process, when given enough time, provides the opportunity for 
  different voices and opinions to be heard.
* For issues where we need a response for the board I'd support  the consensus seeking process,
  help to get any additional information that is needed for the process to move forward, facilitate live
  discussion when necessary and make sure I understand the differing views so that I can reflect this in
  what is brought back to the board discussions.
* In the case where there is a vote to come to a final position, I'd make sure to relate the concerns that
  were voiced along the way, and that there were objections, as I feel that is important context beyond
  simply the results of the final vote.

> you may be `owning` and driving one or more initiatives in the project. how will you position Node.js' collective priority on top of yours?
* Individual initiatives are useful only together with the other initiatives and work going on within the
  project.
* I think it's ok for individuals/organizations to have their own priorities with respect to
  where they invest their time/effort so long as it is in the interest of the overall project and
  that the collective priorities of the project are also moving forward.
* However, in the context of representing the project on the board, the collective priorities
  must come first without any preference for what the board representative is working on.
  The hardest part is for the representative to be aware/know what those collective priorities
  are versus their own initiatives which they will be well versed in. 
* I've tried to work towards things like documented strategic initiatives and the the review in the TSC
  meetings as a way to help capture those collective priorities and that will continue to be
  a priority for me.

 > how will you pursue node's interest with board?
* I will work within the project to clarify issues which are specifically voiced and then 
  ensure that I am knowledgeable enough on the issue to be able to represent the request
  or concern to the board.
* I will ensure that there is enough follow up to make sure the issues that have been voice
  move forward. The existing project board (https://github.com/nodejs/TSC/projects/1)
  seems like a good way to manage this work. 
* In terms of interests which have not specifically called out in advance I'll work to be knowledgeable 
  with the initiatives/activities across the project so that I understand how issues discussed on the board 
  may affect the project. I believe this will let me recognize when I need to get more feedback from 
  project members and bring that discussions back to the project.
* When confidentiality prevents bringing discussion back to the project I believe my 
  involvement/knowledge of what is going on across the project as well as my desire to present
  all aspects of an issue will help me properly represent the interests of the project.

> how will you assess implications of board's direction / decision to Node.js project?
* When possible I'll work to ensure the project is aware/knowledgeable about the board's
  direction/decisions so that I have the input of the project to assess the implications. I'll do this by 
  reporting back to the TSC and Community Committee on board meetings and initiatives.
* When confidentiality prevents information from being shared, I'll assess based on the context
  that I have through my involvement across the different areas in the project.

> how will you tackle situations wherein Node.js' interest is orthogonal to that of the larger JS ecosystem?
* In cases where interests don't align I'll make sure that the interests of the Node.js project
  are well understood and work to find options which minimize the impact to the project.
* Board members have a duty to act in the best interest of the overall Foundation so it will not
  always be possible to act in 100% alignment with Node.js' interests but the Node.js
  representative can be an advocate/champion for options that they feel better aligned
  with those of the Node.js project while still being in the best interest of the Foundation as well. 

> what will you define as success criteria of your role in the board representing Node.js?
* Broadly shared confidence that issues raised have been represented to the board in a way that reflects 
  all aspects of the issue in a fair and balanced manner even if the end result does not make everybody 
  happy.
* Progress on 
  * increasing trust between the board and project members
  * increasing the number of project members who feel there are benefits to being part of the
    Foundation

> what, in your opinion, are the top n advantages of Openjs foundation to the Node + JS ecosystem?
* Simplified message for where supporting companies should invest their resources and funds with 
  respect to JavaScript
* A broader/stronger home for a larger range of JavaScript projects that will allow us to 
  attract and grow other important 'impact' projects to the benefit of Node.js and the other foundation 
  members alike.
* Easier and better defined path to collaboration and opportunity to achieve more than one project 
  could do on its own.
* Opportunity to share Node.js' experience in building/managing a larger scale open source project and 
   to further improve by understanding and leveraging experience from other projects.
* Opportunities for project members to more easily broaden their scope and involvement beyond a 
  single project.

> what, in your opinion, are the top n priorities of the Node.js project at the moment?
* Continued innovation on the technical front and working to enable as many project members
  as possible to help with those efforts (for example the strategic initiatives).
* Continued focus on being open and inviting in order to attract new project members.
* Working to broaden the involvement and total people time that we have supporting our CI 
   infrastructure.
* Growing the amount of end-user feedback and interaction so that use this feedback to help
   steer our decisions within the project.

**Comment by mhdawson** [comment]
One thing to add is that we should probably move the existing project board to the admin repo so as the issues will be covering areas covered by both the TSC and Community Committee.

**Comment by keywordnew** [comment]
Excellent to see the Q/A threads utilized. Thank you for the thoughtful questions and the in-depth answers.

**Comment by mhdawson** [comment]
Election complete, closing.
