### ISSUE TITLE
Node Survey: Question Review

### ISSUE THREAD

**Issue by RRomoff** [nodejs/admin#380]
**Background:**
For the last several years, the Foundation has facilitated a Node adoption survey. The most recent survey results can be found here: https://nodejs.org/en/user-survey-report/
This is the 4th wave of the survey, and we are hoping the extract some interesting trends around adoption and tech use cases.

**Request:**
To ensure no glaring oversights in our questions, we’d like to open up the survey for community review/ feedback. Please make comments/ ask questions directly to the document. 

**The Survey questions can be found here:**
https://docs.google.com/document/d/1DcRB6M7snS-7qJD0kB1RGl9DE2whVNNjM-ubftbsSo0/edit?usp=sharing

Timeline:
Please add your comments and feedback by Tuesday, July 16, 2019. 

Questions?
You may direct questions to Rachel Romoff, rromoff@linuxfoundation.

**Comment by ljharb** [comment]
- you may want to ask how many people vs how many engineers; despite that the LF’s pricing rn is based on total employment, this creates a prohibitive cost for companies that hire an outsized number of non-engineers - so it might help to collect data about how often companies don’t align with the conventional membership pricing rubric.
 - What does “In what language did you learn Node.js?“ mean? are you asking the language i read docs/tutorials in? Are you asking me to put javascript or c++ etc?
 - for gender, only providing two options is both not inclusive, and also insufficient. This would be best as a free form text field with *no* suggested values whatsoever - so that you don’t accidentally suggest value or lack thereof.
 - re number 25, node.js is not a language, so this wording makes no sense.
 - re 33, please include ES5 as an option.
 - 39 is missing a closing paren, and shouldn’t really have a biased suggestion about which node version people should use; it will skew results.
 - 43 and 44: many of these things are not node.js version managers. Perhaps it could be “what tool(s) do you use to install node.js”, and allow multiple selections? Then you could also include “official installers” and “download and compile off the website”.
 - 47: this should be split into two questions; one about which registries and one about which cli tool.

**Comment by gireeshpunathil** [comment]
Few more questions, if you like:

 - how did you embark on Node.js?
    - Through Javascript, that I am familiar with
    - Migrated to Node.js from other stack, motivated by its popularity
    - Architectural consideration - I/O intensive workload characteristics of my app

 - from where you get your node.js issues resolved?
    - nodejs/node repo
    - nodejs/help repo
    - stackoverflow
    - self service

 - what, in your experience is the top Node.js production problem?
    - out of memory / memory leak
    - performance issues
    - unexpected exception
    - crash
    - hang
    - unexpected result

 - how many third party modules you use in your application?
    - none
    - < 10
    - < 100
    - \> 100

**Comment by mhdawson** [comment]
+1 to the questions suggested by @gireeshpunathil

**Comment by bnb** [comment]
+1 to all suggestions by @ljharb, specifically org size and gender. Having a binary gender option is not an option. Will dig in more later today.

**Comment by RRomoff** [comment]
> * you may want to ask how many people vs how many engineers; despite that the LF’s pricing rn is based on total employment, this creates a prohibitive cost for companies that hire an outsized number of non-engineers - so it might help to collect data about how often companies don’t align with the conventional membership pricing rubric.
> * What does “In what language did you learn Node.js?“ mean? are you asking the language i read docs/tutorials in? Are you asking me to put javascript or c++ etc?
> * for gender, only providing two options is both not inclusive, and also insufficient. This would be best as a free form text field with _no_ suggested values whatsoever - so that you don’t accidentally suggest value or lack thereof.
> * re number 25, node.js is not a language, so this wording makes no sense.
> * re 33, please include ES5 as an option.
> * 39 is missing a closing paren, and shouldn’t really have a biased suggestion about which node version people should use; it will skew results.
> * 43 and 44: many of these things are not node.js version managers. Perhaps it could be “what tool(s) do you use to install node.js”, and allow multiple selections? Then you could also include “official installers” and “download and compile off the website”.
> * 47: this should be split into two questions; one about which registries and one about which cli tool.

**Comment by RRomoff** [comment]
> * you may want to ask how many people vs how many engineers; despite that the LF’s pricing rn is based on total employment, this creates a prohibitive cost for companies that hire an outsized number of non-engineers - so it might help to collect data about how often companies don’t align with the conventional membership pricing rubric.
**Yes, we can add this. I’ve made a change in the survey. LMK how that looks**.

> * What does “In what language did you learn Node.js?“ mean? are you asking the language i read docs/tutorials in? Are you asking me to put javascript or c++ etc? **Spoken and written. I added the drop down menu which will make this more clear.**

> * for gender, only providing two options is both not inclusive, and also insufficient. This would be best as a free form text field with _no_ suggested values whatsoever - so that you don’t accidentally suggest value or lack thereof.
**100% agree and this has been a free form text box since the beginning, I’m not sure why the translation is giving us Female and Male but that will be addressed**

> * re number 25, node.js is not a language, so this wording makes no sense.
**Took out part that mentions Node.js in the survey**

> * re 33, please include ES5 as an option.
**Included**
> * 39 is missing a closing paren, and shouldn’t really have a biased suggestion about which node version people should use; it will skew results.
**Deleted the recommendation.** 
> * 43 and 44: many of these things are not node.js version managers. Perhaps it could be “what tool(s) do you use to install node.js”, and allow multiple selections? Then you could also include “official installers” and “download and compile off the website”.
**If not technically accurate, we should update this. However, it will be a new question and not “trendable”  with past year’s data.**

> * 47: this should be split into two questions; one about which registries and one about which cli tool.
**Okay with this change, but need answer recommendations for the questions. Current, answer selections are:
0.00 Other (please specify)
1.00 Npm
2.00 Yarn
3.00 jspm
4.00 duo
5.00 ied
6.00 Bower**

**Comment by RRomoff** [comment]
Thanks for these questions, @gireeshpunathil. I made a few tweaks below. The one thing we want to keep in mind is survey length, so we want to add questions that add considerable value, or even decide what questions no longer add value. One follow up question I have is what are appropriate ranges for the final question? See recommended updates below:


How did you start using  Node.js?
Through Javascript, that I am familiar with
Migrated to Node.js from other stack, motivated by its popularity
Architectural consideration - I/O intensive workload characteristics of my app
I was already familiar with JavaScript
An employer assigned me to work on Node.js
Don’t Know
Other

From where you get your node.js technical issues resolved?
nodejs/node repo
nodejs/help repo
stackoverflow
Google
Youtube
Don’t Know
Other _______

Based on your experience, what do you see as the top Node.js production problem?
out of memory/memory leak
performance issues
unexpected exception
crash
hang
unexpected result
Other
No issues


How many third party modules you use in your application?
none
1-25
25-50
51-75
76-100
More than 100 

> Few more questions, if you like:
> 
> * how did you embark on Node.js?
>   
>   * Through Javascript, that I am familiar with
>   * Migrated to Node.js from other stack, motivated by its popularity
>   * Architectural consideration - I/O intensive workload characteristics of my app
> * from where you get your node.js issues resolved?
>   
>   * nodejs/node repo
>   * nodejs/help repo
>   * stackoverflow
>   * self service
> * what, in your experience is the top Node.js production problem?
>   
>   * out of memory / memory leak
>   * performance issues
>   * unexpected exception
>   * crash
>   * hang
>   * unexpected result
> * how many third party modules you use in your application?
>   
>   * none
>   * < 10
>   * < 100
>   * > 100

**Comment by RRomoff** [comment]
@mhdawson Thanks for your edits! I made changes directly to the survey. Please let me know if I've addresses changes sufficiently!

**Comment by ljharb** [comment]
For 43 and 44, I’d say it’s better to throw out last year’s data on an incorrect question and make sure we can look at trends next year :-)

**Comment by RRomoff** [comment]
> +1 to all suggestions by @ljharb, specifically org size and gender. Having a binary gender option is not an option. Will dig in more later today.

Thanks @bnb! Yes, completely agree RE binary gender option. It's been an open text option in the past and will continue to be so. I'm not sure why the translation only gave two options, but that will be addressed to ensure full inclusion.  The survey is back open for comments, not sure if you've had a chance to dig in but would love your final thoughts be we call this closed. :)

**Comment by RRomoff** [comment]
**UPDATE**
The survey has been updated. Thank you for providing insightful and thoughtful feedback. Please check out comments and provide any required follow-ups. I'll leave the survey open for comments until Wednesday, August 21st. If you have any questions, please let me know. :)

**Comment by gireeshpunathil** [comment]
@RRomoff - thanks; your gradation of values in the last question makes sense to me!

**Comment by mhdawson** [comment]
@RRomoff it still looks like the list of repositories/working groups/projects is out of date

**Comment by mhdawson** [comment]
Other than the list of repositories/working groups/projects in the one question it looks good to me.

**Comment by ljharb** [comment]
@RRomoff thanks! my updated feedback:
 - for the timezone names, since there's often multiple time zone names for a given UTC offset, perhaps it would be good to include in the text description the UTC offset? Additionally, for example, "Pacific Standard Time" only applies for half the year due to daylight savings time - so do I spend more of my time in PST, or PDT? One option might be, "excluding daylight savings time, what time zone / UTC offset do you spend most of your time in"? If not that, then perhaps we'd want to include every item listed [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), but that'd be a long list.
 - question 7 still only says "spoken", should it say "spoken and/or written"?
 - I see you're using the census bureau's [definitions](https://www.census.gov/mso/www/training/pdf/race-ethnicity-onepager.pdf) of race/ethnicity (but also, the "race" question is multiple choice while the "ethnicity" question is free-form, which seems odd). I don't have any concrete suggestions here but something about these questions feels off to me, at least in this context.
 - will question 19 be checkboxes? (i assume so, but it's notated the same as the radio button questions, so i'm confirming)
 - for question 25, a) i assume it's multiple choice, b) should TypeScript be added?
 - i see both "select all that apply" and "check all that apply" and also no specific indication that multiple selections are permitted; should this be made consistent?
 - how is question 32 sorted? it doesn't seem alphabetically, by popularity, or by age, in either direction.
 - questions 37/38 don't mention irc/slack or other online chat communities; should they?
 - for question 39, what does "follow" mean? My personal libraries support node back to 0.6, my personal apps use "current", my previous employer used "last LTS we had time to upgrade to". How would I answer this question?
 - for question 43, you may want to add nvs and volta. also, Docker is not really a node version manager, so perhaps the wording of the question still isn't entirely accurate?
 - as an addendum to question 46, perhaps instead of just asking "how can we better tell you what to do", we should ask "how can we make it easier for you to upgrade"? Moralizing about what version people "should" be on is something the foundation … should … probably avoid :-)
 - for 47, you may want to add pnpm; and you may want to split this question into two: one about "which package management CLI tool are you using" and another "which package source(s) are you using" (ie, npmjs.com, private npm registry, github repos, github package registry, etc)

**Comment by RRomoff** [comment]
> Other than the list of repositories/working groups/projects in the one question it looks good to me.

Awesome! Thanks, @mhdawson . I'll come back with a recommended updated list and would love feedback on if it's accurate/ a recommendation on who might be able to check it.

**Comment by ljharb** [comment]
@RRomoff
 - Pacific Time, and similar, sounds good
 - for questions 37/38 i think it'd be ideal to give slack and gitter and irc explicit mentions
 - for 39, it really depends on what the intention of the question is. If it's asking about what people use in their apps, then "use in production"; if it's asking about what people support with their libraries, then "support"? The two use cases are different, so it's tough to bundle them into one question.
 - for 43: in that case, probably best to keep docker, but maybe rename the question to something like "What tool(s) do you use to manage installed node.js versions?" and let it be multiple choice?
 - for 46, i like your wording
 - for 47 i think splitting it up and making it more accurate is a good idea. Here's what I'd propose:
```
```

**Comment by ljharb** [comment]
@RRomoff
 - Pacific Time, and similar, sounds good
 - for questions 37/38 i think it'd be ideal to give slack and gitter and irc explicit mentions
 - for 39, it really depends on what the intention of the question is. If it's asking about what people use in their apps, then "use in production"; if it's asking about what people support with their libraries, then "support"? The two use cases are different, so it's tough to bundle them into one question.
 - for 43: in that case, probably best to keep docker, but maybe rename the question to something like "What tool(s) do you use to manage installed node.js versions?" and let it be multiple choice?
 - for 46, i like your wording
 - for 47 i think splitting it up and making it more accurate is a good idea. Here's what I'd propose:
```md
1. Which package management CLI tool are you using?
 - npm
 - yarn
 - pnpm
 - jspm
 - duo
 - ied
 - bower

1. Which package source(s) are you using?
 - [ ] npmjs.com
 - [ ] private npm registry (npmE, verdaccio, artifactory, etc)
 - [ ] github package registry
 - [ ] repositories on github.com
 - [ ] other git repositories
```

**Comment by RRomoff** [comment]
@ljharb, thanks for this - comments in line :)


> @RRomoff
> 
> * Pacific Time, and similar, sounds good
**Done**
> * for questions 37/38 i think it'd be ideal to give slack and gitter and irc explicit mentions
**These are added**
> * for 39, it really depends on what the intention of the question is. If it's asking about what people use in their apps, then "use in production"; if it's asking about what people support with their libraries, then "support"? The two use cases are different, so it's tough to bundle them into one question.
**I've read this with "use in production"  in mind but in reading some write in comments, can see the confusion. I recommend we add "use in production" but am open to a question hat covers other use cases.**
> * for 43: in that case, probably best to keep docker, but maybe rename the question to something like "What tool(s) do you use to manage installed node.js versions?" and let it be multiple choice?
**Recommending two questions here, 
**1) What primary tool do you use to manage installed node.js versions?
Choose 1
2)What other tools do you use to manage installed node.js versions? (multiple choice)****

> * for 46, i like your wording- 
**Added this**
> * for 47 i think splitting it up and making it more accurate is a good idea. Here's what I'd propose:
> 
> ```lisp
> 1. Which package management CLI tool are you using?
>  - npm
>  - yarn
>  - pnpm
>  - jspm
>  - duo
>  - ied
>  - bower
> 
> 1. Which package source(s) are you using?
>  - [ ] npmjs.com
>  - [ ] private npm registry (npmE, verdaccio, artifactory, etc)
>  - [ ] github package registry
>  - [ ] repositories on github.com
>  - [ ] other git repositories
> ```

**Added these**

**Comment by ljharb** [comment]
Your comments sound good to me, thanks

**Comment by RRomoff** [comment]
Hi All- I am currently working on getting the survey translated. All feedback has been incorporated and I am closing this issue. Thank you for the help!
