### ISSUE TITLE
cleaning up nodejs/addon-api team

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#396]
Very recently, @gengjiawen requested to be added to @nodejs/addon-api. Looking at the team, I didn't see anyone who had maintainer role (and thus would be able to add them). Given their high activity in core, it seemed reasonable to add them, so I did. But it also made me look at the team composition and I'm wondering if some folks might be best removed. Here's the current people on the team:

@agnat	David Siegel  agnat
@bnoordhuis	Ben Noordhuis  bnoordhuis
@gengjiawen	Jiawen Geng  gengjiawen
@kkoopa	Benjamin Byholm  kkoopa
@ofrobots	Ali Ijaz Sheikh  ofrobots
@TooTallNate	Nathan Rajlich  TooTallNate

So, the reason for removing folks who aren't active are threefold:

* In general, pruning inactive accounts is a good security practice.
* Membership on the team provides administrative access to the node-gyp repo.
* Membership on the team gives access to the private moderation repo.

So, with that in mind, am I right to suspect that there are inactive folks and does it make sense to remove them? I'm unaware of any recent activity from @agnat, @kkoopa, or @TooTallNate, but I invite anyone (especially including them!) to correct me on that. Or maybe there's a good reason for keeping one or more of them? Thoughts?

**Comment by richardlau** [comment]
> - Membership on the team provides administrative access to the node-gyp repo.

I didn't know this (`node-gyp` isn't listed under the list of responsibilities in https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md#addon-api but it says "Responsibilities include" rather than being an exhaustive list). The linked description for the WG from the TSC repo points to https://github.com/nodejs/nan#collaborators for a list of members which looks like it doesn't match the group. 

> I'm unaware of any recent activity from @agnat, @kkoopa, or @TooTallNate, but I invite anyone (especially including them!) to correct me on that. 

At least the first two of those have recent activity in https://github.com/nodejs/nan.

**Comment by agnat** [comment]
o/

As a NAN regular I use the addon-api team mentions to stay informed regarding all things addons.
If that is alright with you I'd like to stay with the team.

**Comment by Trott** [comment]
OK, in that case, maybe I'll just leave the team alone. Thanks!
