### ISSUE TITLE
Document process for a Moderation team member to retire

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/admin#47]
Moderation team members must recertify every year. They also should have a process for leaving, if they are no longer able or want to continue to participate. 

Document:
1. administrative steps/places a member should be removed from lists for contact as a moderator
2. process for member to leave, prob just saying "I am planning to step down" through filing an issue.
3. an emeritus list for Moderation team members in good standing who choose to depart. 
4. dates for every Moderation team member for when their recertification time is due.
5. Activity/participation log for consideration of inactive Moderation team members. What is 'active'? How long does one need to be absent without noting they were taking a break?

**Comment by gibfahn** [comment]
>process for member to leave, prob just saying "I am planning to step down" through filing an issue.

Tiny nit, but a PR moving yourself from active to emeritus is nice, it's an easy way to trace from the readme back to the relevant PR later.

>dates for every Moderation team member for when their recertification time is due.

Discussed in the meeting today, but I think if we could batch this up so everyone gets recertified at once, it would be less manual effort, and probably easier for reviewers to review the whole list at once, rather than a drip-feed of one a month. Doing it the same way we did it for the initial list of members (raise an issue, people can comment if they're -1 or -0 and discussion happens) seems like a good idea.

**Comment by Trott** [comment]
@nodejs/moderation Can we get this documented and in place?

**Comment by ryanmurakami** [comment]
Looks like this will be closed once #97 is merged.
