### ISSUE TITLE
Move gyp-next to the nodejs org

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/admin#475]
Request to move gyp-next (https://github.com/ryzokuken/gyp-next) to the nodejs organization. More context at https://github.com/nodejs/node/pull/32090.

**Comment by targos** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by MylesBorins** [comment]
+1 with the name gyp-next

**Comment by joyeecheung** [comment]
+1

**Comment by rvagg** [comment]
Full context:

GYP is a Google tool, now deprecated by them, we've taken over maintenance of it and it's used in nodejs/node and node-gyp (libuv too, but they're using a pruned-down version and are about to rip it out entirely). We're in the middle of a synchronization effort between the two projects and the repo on question here _should_ be a synthesis of all that so ought to end up as the source of truth for both nodejs/node and nodejs/node-gyp.

We can't just take over the name "GYP" due to copyright concerns. Refael put in a bunch of work to make [GYP3](https://github.com/refack/GYP3) but that stalled in a previous attempt to bring it into the org. The name "GYP3" is also too similar to "GYP". In private discussions (Myles also involved in these on behalf of Google), "gyp-next" was arrived at as the best attempt at a name that was distinct enough from "GYP" that it indicated it was a separate project. Nobody's particularly enamored with the name, it's a pragmatic choice.

If someone has a better name, now would be the time to speak up, otherwise I suspect "gyp-next" is going to be baked in for good.

**Comment by Qard** [comment]
PYG: (Here's the) Project You Generated :laughing:

**Comment by MylesBorins** [comment]
I very much like pyg. Can't get the Beatles song "Little Pygies" out of my
head now.

**Comment by cclauss** [comment]
`pip install pyg` does have a ring to it.

**Comment by Qard** [comment]
Hasn't been updated in seven years. Maybe we could ask to reclaim the name? :thinking: 

Alternatively:

JUNA - Just Use Ninja Already :wink: 
JHEF: Javacript Has Enough Frameworks (so we made one for Python instead)
NACL: Node.js Abstract Compiler Launcher (That'll get us away from Google copyright concerns _for sure_ :trollface: )

More seriously:

NUB - Node.js Universal Builder
JUBE - JSON-based Universal Build Environment

**Comment by richardlau** [comment]
I kind of feel that, boring as it may be, anything that doesn't have "gyp" as part of its name is just going to be confusing.

**Comment by Trott** [comment]
> I very much like pyg. Can't get the Beatles song "Little Pygies" out of my head now.

That'll do: pyg. That'll do.

Er, uh, more seriously, I kinda agree with @richardlau that including `gyp` as part of the name is the user-friendly thing to do.

**Comment by sam-github** [comment]
I agree, to, should have `gyp`. I'm fine with `gyp-next`, the README should be clear that the goal is not to resuscitate gyp or encourage its use for new projects, but to maintain it sufficiently for Node.js addons and libuv.

**Comment by cclauss** [comment]
I would advocate that this module can be `pip install`-ed from PyPI.  My sense is that there has been a lot of unnecessary questions and delay in working with gyp because we have resisted the use of `pip install`.

**Comment by sam-github** [comment]
Can we pip install _and vendor_ it? Node.js build doesn't depend on pip ATM for building, but if pip's a better way to get it into our deps or tools than `cp -r`, I'm OK with using it.

**Comment by cclauss** [comment]
Yes.  pip and vendor can co-exist.

**Comment by bnb** [comment]
SGTM :shipit:

**Comment by ryzokuken** [comment]
> Can we pip install and vendor it?

> Yes. pip and vendor can co-exist.

That's the plan anyway.

Re: the name, @Qard suggested that the "gyp" in the name can stand for "Google Yeets Projects" which is an amazing name IMO as long as it's okay with Google folks (mean no offense, it's just a fact about the past of the project...) @MylesBorins thoughts?

**Comment by ryzokuken** [comment]
@targos the document doesn't exactly say how many approvals are required or how long we should wait until we can proceed with the transfer.

**Comment by targos** [comment]
There's a reference to another document which says we must wait 72 hours.

**Comment by richardlau** [comment]
The link to the other document is broken (I've raised https://github.com/nodejs/admin/pull/476 to fix it).

**Comment by richardlau** [comment]
https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANAGEMENT_POLICY.md#repositories (the corrected link) says (as @targos points out) to wait for 72 hours.

No approvals are required, just no objections in that 72 hour period.

**Comment by nschonni** [comment]
Just curious if this is still a stopgap to keep it alive while a non-Python alternate is proposed?

**Comment by nschonni** [comment]
The GYP license also only only seems to restrict the use of the Google trademark, rather than GYP name

https://chromium.googlesource.com/external/gyp/+/refs/heads/master/LICENSE

> * Neither the name of Google Inc. nor the names of its
> contributors may be used to endorse or promote products derived from
> this software without specific prior written permission.

**Comment by Qard** [comment]
Wouldn’t making it pip installable increase the likelihood people use it for other things, which we specifically _don’t_ want? 🤔

**Comment by cclauss** [comment]
I doubt that anyone is going to find gyp just by search among the +222k packages on PyPI.

**Comment by ryzokuken** [comment]
Done.
