### ISSUE TITLE
archive https://github.com/nodejs/nodejs-ru

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#485]
No commits for a few years now, no issues opened for a couple years, the team should remain of course, and translations can occur in the nodejs.org repo and/or in CrowdIn, but the repo should be archived. Or at least that's my perception. (And unarchiving is no big deal, so even if I'm wrong, this is low risk.)

@nodejs/nodejs-ru @nodejs/i18n @nodejs/community-committee @nodejs/tsc

**Comment by alexandrtovmach** [comment]
@nodejs/i18n team actively working on renew localization process, and now we're thinking about structure of locale teams. This repo and other like this - it's kind of basement for translators to discuss their stuff. Actual translation happens on Crowdin side, so here shouldn't be any commits/PRs, just issues and team guidelines.

When repo is archived there is no way to create new issue, and translators can't join the team or ask to help, that's why I unarchived it.

**Comment by alexandrtovmach** [comment]
related https://github.com/nodejs/i18n/issues/211

**Comment by Trott** [comment]
Ah, sounds good. Maybe all the code should be removed and replaced with a README that explains who is on the team, how the translation process works, and how people can volunteer? (Or content similar to that?) I'll close this issue. Thanks!

**Comment by alexandrtovmach** [comment]
@Trott Yep, that's what I'm going to do
