### ISSUE TITLE
new github team: platform-ibmi

### ISSUE THREAD

**Issue by sam-github** [nodejs/admin#490]
We'd like to make a @nodejs/platform-ibmi team to ping about issues, see https://github.com/nodejs/node/issues/32725#issuecomment-611243162

There's a libuv port to IBMi in progress (almost complete?) and a nodejs one is in-progress as well.

**Comment by richardlau** [comment]
👍. For some context IBM i and AIX are not the same thing (although IBM i PASE provides a means to ["port IBM AIX® applications to the IBM i platform with minimal effort"](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/rzalf/rzalfintro.htm)). 

While it's okay to ping IBMers in any of the IBM platform teams, e.g. platform-aix team, it would be more direct to go directly to the IBM team that maintains the IBM i port of Node.js.

**Comment by cjihrig** [comment]
+1

**Comment by ThePrez** [comment]
For reference, we've had Node.js running since v0.x, but we are just now working to add the platform to the community builds. We are slow like that. :-(

For what it's worth, market research shows a whopping 26% of IBM i customers are using Node.js (#NotATypo)!

If we have a Node.js platform team, I would suggest the same members as @libuv/ibmi

**Comment by bnoordhuis** [comment]
> I would suggest the same members as @libuv/ibmi

Said team consists of the following people:

@kadler
@markdirish
@ThePrez
@mgoffmn
@abmusse

**Comment by Trott** [comment]
+1

**Comment by targos** [comment]
+1

**Comment by addaleax** [comment]
Done, created the team and invited the people from the libuv team + @dmabupt who was suggested in the referenced issue.
