### ISSUE TITLE
#nodejs-core (or #nodejs-dev) channel on the OpenJS Foundation Slack?

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#549]
Since https://github.com/nodejs/admin/issues/53 a lot has changes. The Node.js and JS foundation got merged, and the new foundation has an official Slack: https://slack-invite.openjsf.org/. Many projects have channels there, and many Node.js working groups do as well. I'm wondering if we could create a #nodejs-core (or #nodejs-dev) channel there. We can also have an IRC app linking to the #node-dev freenode channel (similar to what we do with #node-build) if we want to keep both channels connected.

**Comment by ljharb** [comment]
The slack-irc bridge (in build, but also everywhere else I've tried it) is a very unpleasant and awkward experience on both ends in my experience, albeit slightly nicer on the Slack side. I think that if "not IRC" is preferred (personally, I prefer IRC), it would be better to disconnect from IRC entirely rather than the subpar bridged experience.

**Comment by mmarchini** [comment]
Right, I guess that's another option: having IRC and Slack as separate channels. The bridge is not ideal but is a compromise between users who prefer IRC or Slack since we'll never be able to satisfy both types of user.

**Comment by mhdawson** [comment]
I personally find Slack easier to keep connected/engaged that IRC.  It is being use more within the foundation and I think creating nodejs-core there would make sense.

**Comment by BethGriggs** [comment]
+1 for having a #nodejs-core/#nodejs-dev (or similarly named) channel in the OpenJS Slack

**Comment by mmarchini** [comment]
Created [#nodejs-dev](https://openjs-foundation.slack.com/archives/C019Y2T6STH)
