### ISSUE TITLE
Create nodejs/social-team repo

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#586]
There's some discussions that could be beneficial to have well documented and public for the Social Team. A repo outside of nodejs/tweet would be an ideal place for that :)

**Comment by Trott** [comment]
No problem from me for creating a repo. I would prefer it be unambiguously named, so `social-media` might be better than `social` so that someone doesn't have to click through only to find out that it's not about Node.js happy hours and meetups. But that's just me offering my unsolicited opinion and not blocking on anything. Call it whatever works for you and everyone else.

**Comment by mhdawson** [comment]
+1

**Comment by jasnell** [comment]
No objections here.

**Comment by bnb** [comment]
It's been more than 72 hours, since this was proposed with no objections. Per my understanding of the repo's documentation, we can go ahead and create this. I'll do that. If it needs to be undone, I can also do that.

**Comment by joesepi** [comment]
I'm closing this since the repo has been approved and created. Thanks!
