### ISSUE TITLE
Audit of teams

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#592]
As part of the discussion in https://github.com/nodejs/admin/issues/519 it was suggested we should do a broader audit.

Opening this issue to discuss, move that forward.

**Comment by Trott** [comment]
Just did a very quick and superficial audit of teams and would recommend eliminating the following that all seem defunct.

@nodejs/enterprise-advisory-group 
@nodejs/nodetogether 
@nodejs/onboarding
@nodejs/code-and-learn

**Comment by Trott** [comment]
The following localization teams each have only one member and no significant activity in their corresponding repositories since 2015 or maybe 2016 in one case. They would seem to be obvious candidates for deletion, although not having the groups would possibly discourage people from realizing that they could join and start localization. (Although the fact that no one has joined since 2015 argues against that being likely, I suppose. I'd also argue that people might be more energized if they are *starting* a group than joining a long inactive one.) They all date back to the io.js call for volunteers for localization in 2015.

@nodejs/nodejs-bg 
@nodejs/nodejs-cs
@nodjes/nodejs-fi
@nodejs/nodejs-pl 
@nodejs/nodejs-sw 
@nodejs/nodejs-ta

**Comment by bnb** [comment]
> @nodejs/enterprise-advisory-group
> @nodejs/nodetogether

+1 to these. They were both CommComm groups that started but never accellerated.

>@nodejs/code-and-learn

Was this one ever used? If so, is it now defunct simply because of COVID and the lack of in-person events, or are we done with code and learns?

**Comment by Trott** [comment]
> Was this one ever used? If so, is it now defunct simply because of COVID and the lack of in-person events, or are we done with code and learns?

Good question. I don't know that we're necessarily done with Code & Learn events--I stepped away long before COVID because I didn't want to burn out but I could see wanting to do them again with some modifications--but that team is addaleax, trivikr, and me. On the one hand, none of us have been actively involved in Code & Learn events in years. On the other hand, it's not like the three of us aren't active on the project in various capacities, so we don't get a whole lot from removing that team. I'm OK to leave it alone for another year or three before deciding what to do with it.

**Comment by trivikr** [comment]
The team @nodejs/code-and-learn was created when we were actively organizing Code and Learn events back in 2017 and 2018. It's no longer used and I'm OK if it's eliminated.

**Comment by joyeecheung** [comment]
> @nodejs/enterprise-advisory-group
> @nodejs/nodetogether
> @nodejs/onboarding
> @nodejs/code-and-learn

+1 to all of these - I think we rarely use these to ping on GitHub nowadays

**Comment by Trott** [comment]
> > @nodejs/enterprise-advisory-group
> > @nodejs/nodetogether
> > @nodejs/onboarding
> > @nodejs/code-and-learn
> 
> +1 to all of these - I think we rarely use these to ping on GitHub nowadays

Deleted those four and archived the nodetogether repo while I was at it.

**Comment by Trott** [comment]
Archived nodejs-fi repo and removed nodejs-fi team. Remaining to be evaluated/completed:

- [ ] @nodejs/nodejs-bg 
- [ ] @nodejs/nodejs-cs
- [ ] @nodejs/nodejs-pl
- [ ] @nodejs/nodejs-sw
- [ ] @nodejs/nodejs-ta

**Comment by Trott** [comment]
> @Trott given that we've seen no ping from those folks, probably deletable?

All deleted. I'll also remove any people from the org that aren't on any teams anymore. Closing this. Thanks.
