### ISSUE TITLE
Limiting who can approve/request-changes on pull requests in the nodejs/node repo

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#652]
Today, I noticed a setting that permits us to limit who can approve/request-changes on a pull request to people who have explicit read-or-higher access to a repository. I've turned this on for the nodejs/node repo to (hopefully) eliminate spam/bot approvals, which have certainly been a problem from time to time (and generate a lot of notification spam).

![image](https://user-images.githubusercontent.com/718899/147804657-488c8af5-8b3f-47fe-aaec-b787fcd97153.png)

**Comment by Trott** [comment]
@nodejs/moderation @nodejs/tsc

**Comment by benjamingr** [comment]
That's great and hopefully will reduce some review spam - thanks for the update

**Comment by mmarchini** [comment]
The only downside IMO is when we request reviews from a WG, since this will prevent non-committers that are part of the WG from approving. All in all I think that's still a positive change and we should at least experiment with it for a while. If it turns out to be more harmful than good we can always revert (but I doubt it).

**Comment by ljharb** [comment]
@mmarchini if they're part of the WG, i think you can add the WG github team as a reviewer, and they'd still be able to leave reviews

**Comment by mmarchini** [comment]
ohhhhh, interesting, I didn't know adding the team as reviewer would do that.
