### ISSUE TITLE
Transferring in repo `loaders-test`

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/admin#674]
Hi, yesterday I transferred in the repo https://github.com/nodejs/loaders-test without realizing that there’s a process for this. My apologies. Moving that repo here has been a TODO item for the loaders team for over a year, as we test the loaders API against the examples in that repo. I just learned of https://github.com/nodejs/admin/blob/main/transfer-repo-into-the-org.md, I’ll be following the steps in there soon.

**Comment by aduh95** [comment]
/cc @nodejs/tsc 

I've added @nodejs/loaders as maintainers of [nodejs/loaders-test](https://github.com/nodejs/loaders-test).

**Comment by mhdawson** [comment]
@GeoffreyBooth thanks for the heads up and making sure we are consistent with https://github.com/nodejs/admin/blob/main/transfer-repo-into-the-org.md in terms of the end state.

**Comment by GeoffreyBooth** [comment]
Thanks, I think I’ve done everything that should be done? Please let me know if there’s anything else.

**Comment by mhdawson** [comment]
As per [the ](https://github.com/nodejs/admin/blob/main/GITHUB_ORG_MANAGEMENT_POLICY.md#repositories) I think we can consider the request to transfer it in retro-actively approved since the tsc was at mentioned over 72 hours and from what I can see the other required files are there so I think its done and the issue could be closed.
