### ISSUE TITLE
Create nodejs.org private fork for release announcement

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/admin#675]
Historically we've drafted the major release announcements in a restricted OpenJS Google Doc and then posted the content to the Node.js Medium and https://openjsf.org/blog. 

This year I propose we post the Node.js 18 major release announcement to nodejs.org. (IMO, that's the logical place where end users would be looking for official release content.). Posting it to nodejs.org also means we can use the PR process to enable contributions and reviews from our collaborators.

One challenge is that OpenJS coordinate with press and have embargoes around the major Node.js releases. So, to work around this, I am requesting to create a temporary private fork of nodejs/nodejs.org to craft the release announcement. The repository can be deleted once the release post is live. The reason to create this as a private fork (rather than use nodejs-private) is to enable as many collaborators as possible the opportunity to contribute/have their work highlighted. I'd plan to add all Node.js collaborators, but would also like to add our OpenJS marketing support contacts (Alix et al.) to the repository.

**Comment by Trott** [comment]
> Not going to block the proposal but I wonder what would go into the release announcement that would be private until the embargo that wouldn't be in the publicly visible release post (the one with the changelog) that has traditionally been (and currently is) publicly visible in the core repo.

The OpenJS Foundation folks would have to answer this definitively, but I imagine the embargo isn't about the factual content about the release. I imagine it's about the actual text, and maybe some quotes from some folks. "Michael Dawson, Senior Node.js Person Of Note at Red Hat, says, 'This is the most significant new release of Node.js since our last release!'" That kind of stuff.

**Comment by Trott** [comment]
"Node.js 18 is significant because, at least in the United States, Node.js can vote now. 18 is a really, really, big number. It is bigger than 17, if you can believe that, and that was the integer we assigned to our last release. We've really outdone ourselves here!" said Rich Trott, currently seeking employment after being fired for "having an alarminigly magnified sense of his ability to be funny."

**Comment by nschonni** [comment]
Definitely not what it is intended for, but I wonder if you could abuse the Security Advisory feature https://docs.github.com/en/code-security/repository-security-advisories/creating-a-repository-security-advisory

**Comment by BethGriggs** [comment]
> Not going to block the proposal but I wonder what would go into the release announcement that would be private until the embargo that wouldn't be in the publicly visible release post (the one with the changelog) that has traditionally been (and currently is) publicly visible in the core repo.

I have raised the question of whether the embargo is necessary considering the content of the release is always publicly known in advance via the proposal (as we discussed last week, @richardlau). I haven't had a response on that just yet. I do believe that the concern is around other press lifting the words verbatim and publishing it prior.

Part of the intent of moving from a OpenJS/TSC-restricted doc to a nodejs.org GitHub PR was to enable the process to be opened up, so I'd be happy if this repository ended up not being necessary.

**Comment by mhdawson** [comment]
I think the main reason in the past has been that there is a goal to make a "marketing splash", get press interested in writing articles etc. From what I understand that does not work very well if the info/details are already public/published.  @arobinsonLF, @rginn should be able to add more explanation/confirm if that is correct.

I suggest we proceed with this proposal so that we get started and if it later turns out it does not need to be private we can  just move the PR to the node.js or repo.  I think it will already be better in terms of getting broader input than what has been used before.

+1 on the proposal/creation of the private fork.

**Comment by BethGriggs** [comment]
https://github.com/nodejs/nodejs.org/commit/b6619fca48c4b8fe29379d1747b137e82467cf9b is the content that was created in this private fork. Deleting the repository now.
