### ISSUE TITLE
remove accounts that are in zero teams

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#713]
There are people in the nodejs org who have either removed themselves from their last team or else have been removed through some other process. To help clean things up and keep it maintainable, I'd like to remove people who have zero teams. But sometimes people can be very surprised when they get the GitHub notification email saying they've been removed from the org. And once or twice, someone has protested to me privately, saying that there's no reason not to leave them in the org. I have mixed feelings about that. 

If you are in favor of removing accounts from the GitHub nodejs org that are not members of any teams, no need to leave a comment (unless you think you have something to say that I haven't covered). A 👍 reaction is appreciated, though. 

On the other hand, if you think there are good reasons *not* to do this, I'd like to read what you have to say about it! Please comment.

I'll put a list of all the people that would be affected at this point in time so they know this is coming and/or can comment if they wish.

**Comment by nschonni** [comment]
Related https://github.com/nodejs/admin/issues/651

**Comment by Trott** [comment]
Accounts that would be affected (unless we add them to another team or decide that we're not doing this):

@ahmadnassri
@allevo
@amandeepmittal
@aoberoi
@aruneshchandra
@AustinWinstanley
@AyushG3112
@bcmarinacci
@bdharrington7
@bentinata
@bf4
@bjb568
@bluesockets
@chris--young
@ckotzbauer
@craftninja
@ctsuei
@davidfekke
@daxlab
@Delapouite
@detailyang
@dmcghan
@drzippie
@dshaw
@ErnestoSalazar
@expitly
@fbaiodias
@gentios
@glennschler
@gonenduk
@gtewallace
@hackygolucky
@indexzero
@isaacs
@jalafel
@jbottigliero
@jchip
@jrit
@justsml
@knpwrs
@kohei-takata
@kyh
@LinusU
@marc-maurer
@marswong
@MassimilianoMura
@mattc41190
@MikeyBurkman
@mkdolan
@mrkiffie
@naskapal
@Neil188
@nickmccurdy
@nodech
@osk2
@paazmaya
@paulgrock
@pboivin
@petetnt
@pidofme
@pin3da
@preco21
@Qantas94Heavy
@rbnswartz
@reedloden
@rgbkrk
@robertkowalski
@RRomoff
@ruggertech
@SamuelBolduc
@sinaomrani
@sonicdoe
@stevemao
@Stichoza
@TheHollidayInn
@therebelrobot
@tombusby
@trevorah
@Tsuna-mi
@undownding
@uyu423
@WaleedAshraf
@webysther
@wentout
@xcatliu
@Yash-Handa
@ykzts
@yodeyer
@yorkie
@yuryu
@ZibbyKeaton

**Comment by Trott** [comment]
I'm going to add @WaleedAshraf back to `@nodejs/website` and remove them from the list. They've been active in reviewing a handful of PRs in the nodejs.org this year, and that's plenty of reason to be on the team.

**Comment by Trott** [comment]
Affected people list part 2 (broken up into two lists because apparently there is a limit to how many names you can @-mention in a GitHub comment):

@naskapal
@Neil188
@nickmccurdy
@nodech
@osk2
@paazmaya
@paulgrock
@pboivin
@petetnt
@pidofme
@pin3da
@preco21
@Qantas94Heavy
@rbnswartz
@reedloden
@rgbkrk
@robertkowalski
@RRomoff
@ruggertech
@SamuelBolduc
@sinaomrani
@sonicdoe
@stevemao
@Stichoza
@TheHollidayInn
@therebelrobot
@tombusby
@trevorah
@Tsuna-mi
@undownding
@uyu423
@webysther
@wentout
@xcatliu
@Yash-Handa
@ykzts
@yodeyer
@yorkie
@yuryu
@ZibbyKeaton

**Comment by petetnt** [comment]
Honestly only reason I hadn't left was because I couldn't find a leave button on the organization page, for whomever is looking for it it can be found in your settings https://github.com/settings/organizations

**Comment by ruggertech** [comment]
being in the org allows me to stay informed.

**Comment by Trott** [comment]
> being in the org allows me to stay informed.

Can you explain that a bit more? What do you do to stay informed that you wouldn't be able to do if you weren't a member of the org?

**Comment by Trott** [comment]
@nodejs/tsc (for awareness)

**Comment by justsml** [comment]
Can you add me back to the website team?

**Comment by ovflowd** [comment]
> Can you add me back to the website team?

Are you currently contributing to the website repository? 👀 (Just by a quick look, it seems the last time you contributed was on 2018 https://github.com/search?q=commenter:justsml+org:nodejs, https://github.com/search?q=author:justsml+org:nodejs)

**Comment by GeoffreyBooth** [comment]
@isaacs is working on PRs to move some packages into core.

**Comment by aduh95** [comment]
> @isaacs is working on PRs to move some packages into core.

Being or not in the org changes nothing to that, right?

**Comment by webysther** [comment]
I've been away for a while and I'm returning now, could you keep me on the time to website?

**Comment by mhdawson** [comment]
One additional suggestion which is optional and should not block or delay removing people as you suggested is that it would be good to document this as standard practice in our GITHUB_ORG_MANAGEMENT_POLICY.md]( (https://github.com/nodejs/admin/blob/main/GITHUB_ORG_MANAGEMENT_POLICY.md), most likely in the `members` section.

**Comment by justsml** [comment]
@ovflowd you are correct, that's my last merge there. However I have been on some of the zoom calls over the last year or 2, and recently I've been finding more time to contribute to the OSS projects I ❤️. (This is fairly recent, and to see that my efforts are trending toward more OSS work, I've recently landed small to medium PRs in aws-sdk-mock-client and Netflix's Pollyjs.)

While it's not visible in this GitHub org, I have been working on various bits of Promise/async content to hopefully bring into the official docs (I was discussing this with @benjamingr about a year+ ago.) This got delayed because I sold a (temporary) license for my content which reverts back to me in October - at that point I will be very excited to contribute.

**Comment by indexzero** [comment]
I believe my membership was from the website team, then as a Board member, and most recently as a member of the `package-maintenance` WG. Not as active in that WG as I'd like to be – but would still consider myself a member via a long standing "proxy": @rxmarbles

No strong feelings here so up to y'all @Trott @mhdawson (et al) what you'd like to do 🙏🖖

**Comment by bnb** [comment]
I am +1 to removing anyone who isn't explicitly a member of a WG. As far as I know, this shouldn't prevent anyone from contributing and I'd be happy to fast-follow with support to join relevant WGs if they *are* doing work in a WG but are not currently a member. The barrier to re-joining upon becoming active again is very low, so if people want to be a member they should participate actively in the project's work.

After having been a member of this organization coming up on a decade, I genuinely believe one of our biggest mistakes was having a low barrier to entry and no plan of managing inactive contributions - this is something I recognized early in the Website WG but wasn't experienced enough to fully understand the impact of. This has led to the awkward state we're in now where people want access but aren't contributing, and being removed feels harsher than it actually is given the low barrier to entry/re-entry. We've lost velocity in a number of spaces because of this, and I'm happy to see us beginning to course correct more broadly on that (rather than in individual cases, like teams/WGs/initiatives that have implemented Emeritus).

**Comment by Trott** [comment]
> I am +1 to removing anyone who isn't explicitly a member of a WG.

I agree with @bnb and want to clarify that this applies not just to WGs (working groups), but also to all GitHub teams in the org, including those that are not officially chartered working groups.

**Comment by Trott** [comment]
I've added the `tsc-agenda` label in the hopes that we can arrive at a decision at or before the next meeting (in one week) to either do this or close this issue. @nodejs/tsc

**Comment by Trott** [comment]
@nodejs/tsc Can you give a 👍 reaction to this if you'd like us to move forward with this, and a 👎 if you have concerns/doubts and would want this to at least wait for the next meeting? I see 👍 above from targos, aduh95, and RaisinTen. Anyone else?

**Comment by Trott** [comment]
I've gone ahead and removed accounts that are in zero teams. If you feel like you were removed in error, please leave a comment or get in touch. (My email is in my GitHub profile.) Thanks, everyone!
