### ISSUE TITLE
Self-nomination: Nominate @ovflowd to the Moderation Team

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#793]
As @benjamingr [mentioned here](https://github.com/nodejs/node/issues/47672#issuecomment-1534278670), we don't have many moderators, and whilst I might not be the greatest of fits (language barriers, communication barriers, bias), I definitely would like to keep the org safer :)

So, I'd be a pleasure to help!

**Comment by Trott** [comment]
@nodejs/tsc

**Comment by mhdawson** [comment]
+1

**Comment by benjamingr** [comment]
(A good opportunity to also prompt some pinged TSC members to join the team :))

**Comment by benjamingr** [comment]
It looks like the nomination passed :) can someone from the TSC on-board? @Trott @aduh95

**Comment by Trott** [comment]
I can do it later this month if Antoine doesn't do it first. The TSC needs to re-certify the current Moderation Team members anyway, so maybe we can onboard/offboard all at once.

**Comment by benjamingr** [comment]
I can do it (there is no actual requirement in the ONBOARDING document for it to be a collaborator or a TSC member afaik ) I just personally preferred you or Antoine since you probably did it before, sorry for volunteering you!

@ovflowd can you shoot me an email to benjamingr@gmail.com or a message (just tell me where!) to coordinate? Most of the onboarding is very technical but I do think there is value in doing it in person rather than just sending invites to slack etc.

**Comment by ovflowd** [comment]
Hey @benjamingr are you on the OpenJS Slack? :)

**Comment by benjamingr** [comment]
Sent a message there to coordinate :)

**Comment by Trott** [comment]
@benjamingr @ovflowd Is there anything remaining to be done on this, or can this be closed?
