### ISSUE TITLE
Enable `GITHUB_TOKEN` "write" permissions when stated explicitly

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#811]
As mentioned over here: https://github.com/nodejs/nodejs.org/issues/5575

And documented over https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#changing-the-permissions-in-a-forked-repository and https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository.

States that this option needs to be manually enabled org-wide to take effect. I've noticed that we have "read and write" permissions enabled for repositories like `nodejs/node` and `nodejs/nodejs.org` (and others), but the org-wide setting was disabled.

~Since apparently, the intent was to leave that on; I've enabled this option org-wide (which should still respect individual repository settings, but when it's off org-wide, it ignores repository settings. (Double note that enabling this setting has no consequences! And it does not override repository settings! It only allows repositories that have this enabled already to have their settings respected!)~ Apparently this setting is only for private repositories, meaning it has no effect on public repositories.

On a side note, I would state that `nodejs/node` current GitHub Actions security settings maybe are way too lenient and probably vulnerable to other patterns of attacks?

For example, I would recommend changing these settings on `nodejs/node` to the ones I've labeled with red:

![image](https://github.com/nodejs/admin/assets/12037269/fd7b6cc5-a844-4ce4-ad1d-929881d75035)

![image](https://github.com/nodejs/admin/assets/12037269/e7dcf49b-b654-4edd-8864-84680b24bbee)

![image](https://github.com/nodejs/admin/assets/12037269/8cb5c8d3-f6d4-485b-80ef-760fd4111873)

I do not know what Workflows exist on `nodejs/node`, but I assume they're safe either way or probably do not have anything dangerous that could allow some security vulnerability. (Also, `GITHUB_TOKEN` are only valid in the context of the Workflow they're running)

I'm opening this issue to let you know that the setting changed and is a recommendation/debate about revising our GitHub Actions runner settings.

cc @ljharb (as I believe you're working on the Sovereign Tech Fund for eval' Node.js Security?)

and cc @nodejs/tsc for awareness and discussion of what we should do?

**Comment by ovflowd** [comment]
FYI: I've reverted the change, as 1st, they seem to only apply for "private repositories," so it does not apply to any of the repositories I've mentioned before, and 2nd, because I definitely should not have done that 🤦 (Like, the only reason I have access to that, is due to a circumstance that should not allow me to do that)

Anyhow, I guess my arguments still stand that we should probably enforce security settings over here 👀

**Comment by ljharb** [comment]
The current settings seem perfectly fine to me, and are what i use on all of my projects.

Certainly each workflow should state permissions explicitly, and if there’s concern about external actions they can be depended on by sha instead of by tag (at the cost of needing an explicit update to get bugfixes and security fixes), and if there’s concern about exfiltration, the Step Security Harden Runner can be used.

Is there a specific concern you have in mind?

**Comment by ovflowd** [comment]
What I’m afraid is about first time contributors making a legit first PR and then once that gets merged a malicious follow-up PR. With current settings that would be 100% doable. Since we only require approval for first time contributions 👀

**Comment by ovflowd** [comment]
Also I would recommend passing an explicit allowlist of actions that are allowed to run and pin their versions 🙈

**Comment by aduh95** [comment]
We added approval for first-time contributors because there had been a spike of spammers that were trying to abuse gha to mine cryptocurrencies. The current setting was enough, we haven’t seen any more of those PRs. I’d be -1 to restrict the current setting further, it’s not like running gha on not-quite-relevant PRs was costing us money, on the other hand it’s quite a pain to land PRs if we also have to remember to approve CI every time. If someone wants to make a legit contribution to node and then they open a malicious PR, we keep the legit contribution and the user gets a block, it’s clearly a win for us.

**Comment by ljharb** [comment]
What malice could be caused? Generally, nothing that’s done on a PR has any potential negative impact except time/usage.

**Comment by ovflowd** [comment]
> What malice could be caused? Generally, nothing that’s done on a PR has any potential negative impact except time/usage.

Well I'm referring more about cache's being poisoned, tokens and secrets being stolen or stuff like that. But if y'all think it's alright, then let me close this issue!

Thank you for your time anyways!

**Comment by aduh95** [comment]
I don't think we use any caching on nodejs/node, and tokens and secrets should not be accessible to forked repositories anyway.
