### ISSUE TITLE
Grace Hopper Day - Create a temporary label

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/admin#835]
Hey folks!

Today is the GHC (Grace Hopper Celebration day) and as usual, we have some issues to work on we would like to create them on nodejs/node/issues but with a specific flag (grace-hopper-day). So we can measure and organize the tasks efficiently. I am opening this issue to inquire if anyone is opposed. If so, please provide details.

name of the tag: `GHC23`

**Comment by tniessen** [comment]
IIRC, in the past, we just added the existing `code-and-learn` label to any C&L pull requests and did not create any issues.

**Comment by RafaelGSS** [comment]
I think we have just a few mentors this time. I believe it will make things a bit harder since attendees will need to wait for a sync availability. Maybe we can resolve it through github issues?

**Comment by joyeecheung** [comment]
For code-and-learns I think we usually just print a bunch of very specific tasks out (e.g. change var to let in test/parallel/some-test-name.js) and give them to people, but that would take a lot of work (h/t to Rich who used to do this). My two cents is that you might want to use some dedicated channel to communicate about these tasks instead of using the main issue tracker. That may make things easier to find for the participants.

**Comment by tniessen** [comment]
> we usually just print a bunch of very specific tasks out (e.g. change var to let in test/parallel/some-test-name.js) and give them to people, but that would take a lot of work

@joyeecheung That's what we ended up doing :)

**Comment by RafaelGSS** [comment]
We're using them, thanks folks!
