### ISSUE TITLE
Request access to new GitHub issues features

### ISSUE THREAD

**Issue by targos** [nodejs/admin#921]
Refs: https://github.blog/changelog/2024-10-01-evolving-github-issues-public-preview/

I'd like to add the nodejs org to the waitlist. I think sub-issues and issue types will be very useful to us.

**Comment by RedYetiDev** [comment]
FWIW IMO the 2 main features:

Issue Types: https://github.com/orgs/community/discussions/139933 - Instead of labeling issues as “Feature Request” or “Bug” (which we don’t have), GitHub will support a classification of issue types, alongside the traditional labels.Sub Issues: https://github.com/orgs/community/discussions/139932 - Currently, we use tracking issues to manage different long-term tasks, however GitHub is introducing sub-issues, a way to open an issue that is a part of another issue.

**Comment by RedYetiDev** [comment]
IMO the following additions will be useful:

1. Issue Types: https://github.com/orgs/community/discussions/139933 - Instead of labeling issues as “Feature Request” or “Bug” (which we don’t have), GitHub will support a classification of issue types, alongside the traditional labels.

2. Sub Issues: https://github.com/orgs/community/discussions/139932 - Currently, we use tracking issues to manage different long-term tasks, however GitHub is introducing sub-issues, a way to open an issue that is a part of another issue.

**Comment by richardlau** [comment]
> I think sub-issues and issue types will be very useful to us.

Personally, I'm looking forward to:
> * On long issues, selecting ‘load more’ will now fetch 150 events instead of 50.

🙂

**Comment by mcollina** [comment]
I've heard that it fails to load repositories with more than 1000 open issues :(.

**Comment by targos** [comment]
@mcollina Is there a public discussion about this? I wouldn't like block on rumors.

**Comment by mcollina** [comment]
No I don't atm :(

**Comment by targos** [comment]
The `microsoft/typescript` repo has more than 5k issues open and is enrolled in the feature: https://github.com/microsoft/TypeScript/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

**Comment by legendecas** [comment]
Given with the precedent on `microsoft/typescript` repo with more than 5k issues, any concerns with moving ahead on this?

**Comment by RedYetiDev** [comment]
IMO we should, before moving forward, decide what "Types" to add (if any), just so we are all aware.

**Comment by targos** [comment]
Here are the default issue types:
![image](https://github.com/user-attachments/assets/e5a5e844-aa61-4e58-aca1-4051bc7dfb65)

**Comment by ovflowd** [comment]
> Here are the default issue types: ![image](https://private-user-images.githubusercontent.com/2352663/384835461-e5a5e844-aa61-4e58-aca1-4051bc7dfb65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTM2NTcsIm5iZiI6MTczMTMxMzM1NywicGF0aCI6Ii8yMzUyNjYzLzM4NDgzNTQ2MS1lNWE1ZTg0NC1hYTYxLTRlNTgtYWNhMS00MDUxYmM3ZGZiNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMDgyMjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUxNjYwOWM0YTFlMzVlYWZiNjIzOWQ1YjM2ZWU0OGMzMDdmMTBlODZiNGQ4MjVhZTRkMWIwMWM3Nzk2YzVlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.j6LuHJ1Q8KIp4SJwhWUPIi_K2wHBG_8_GWktJADhsRU)

I feel we should have some based on the core labels we have? Not sure Task and Enhancement make sense. Bug, Feautre, Docs, Tooling, etc make sense for me.

**Comment by targos** [comment]
I just requested access.

They just released some new stuff: https://github.blog/changelog/2024-12-12-github-issues-projects-close-issue-as-a-duplicate-rest-api-for-sub-issues-and-more/

**Comment by targos** [comment]
It's now enabled.
